### ISSUE TITLE
Running in docker

### ISSUE THREAD

**Issue by shawnmclean** [PeterKottas/DotNetCore.WindowsService#1]
Do you know why I'd get a `PlatformNotSupportedException` when running your example inside a docker container using `microsoft/dotnet:1.1.0-runtime` image?

It throws this exception after the service factory returns a new instance of my service (which is empty and inherited from IMicroservice). The exact example you have.

**Comment by PeterKottas** [comment]
Hi @shawnmclean thanks for giving this lib a go :) I must admit I didn't try it on docker so far although it's a high priority for the future. I should be able to look into this during the weekend. Windows services are quite difficult concept and I know historically it didn't work with docker at all. But now with windows containers ... things might have changed. I'll let you know when I found out more and in the meantime, any effort to solve this yourself would be much appreciated.

**Comment by PaulCoetser** [comment]
Hi Peter, 

I'am trying out your library, and I think I almost got it to work, but I struggle a little to get it "registered" into the "local services" of control panel.

Another thing I'am trying to get running is to host a WebAPI with this service.
In my project I use your ExampleServiceTimer and change the Start() to the following:

public void Start()
    {
      this.StartBase();
      Timers.Start("Poller", 1000, () =>
      {
        File.AppendAllText(fileName, string.Format("Polling at {0}\n", DateTime.Now.ToString("o")));
      });
      
      _host = new WebHostBuilder()
         .UseKestrel()
         .UseContentRoot(Directory.GetCurrentDirectory())
         .UseIISIntegration()
         .UseStartup<Startup>()
         .Build();

      _host.Run();

      Console.WriteLine("I started");
      File.AppendAllText(fileName, "Started\n");
    }

The _host is the normal .netcore way to run a WebAPI, but it blocks the thread on _host.Run()
So it never reach the next line until I kill the service.

Do you know how I can use your service to host a WebAPI?

Thanks

**Comment by PaulCoetser** [comment]
Hi Peter,

I'am using this library and I do struggle a little to setup this service.

I get it to install my service and start the service.  The service name / description I provide gets converted to lower case (when viewed in the local services).
 
public static void Main(string[] args)
    {
      ServiceRunner<ExampleServiceTimer>.Run(config =>
      {
        config.SetName("MY Service");
        config.SetDescription("This service host a WebAPI");
      }
   }

another question is when the service is already installed and started and I try to "install" it again I get a dotnet already inuse exception.  It somehow does not do the "ReInstall"

When I debug your library the config.Action enum remain on "RunInteractive" even when I pass in "action:install"

Thank you

**Comment by dasMulli** [comment]
As long as there are calls to any windows service API, a `PlatformNotSupportedException` is expected on linux-based docker images. You could try the `microsoft/dotnet:1.1-runtime-nanoserver` images.
However, if you build a docker image from .net core apps, you should be fine with just a console app that is set as the container's entry point (or an image's entry point if you publish it).

**Comment by PeterKottas** [comment]
Thanks mate certainly helpful. Especially the last part. I think that's enough for closing this as there doesn't seem to be a point of having this if you can run console app directly.
