### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by lefig** [PeterKottas/DotNetCore.WindowsService#101]
Hi Peter,

Firstly, this is not an issue but rather expression of appreciation for an excellent project. 

I have a query regarding installation.

Do I pass "action:install" as a command line parameter?

Many thanks

Fig

**Comment by thepersonclass** [comment]
I believe it would be something like this cd to your bin folder of you project.

yourservice.dll action::install

I tried this with the sample project though and got an issue where its looking for a System.Runtime 4.2.0 and could not find this dependency.

**Comment by lefig** [comment]
Thanks Peter. I will give it a try.
