### ISSUE TITLE
Can there be more than on Service

### ISSUE THREAD

**Issue by Xtremrules** [PeterKottas/DotNetCore.WindowsService#118]
I wish to know if there can be more than be more than one `ServiceRunner<T>.Run(...){}` in the startup method.

```cs
class Program
{
	public static void Main(string[] args)
	{
		ServiceRunner<ExampleService1>.Run(config =>
		{
			/// implementation
		});

		ServiceRunner<ExampleService2>.Run(config =>
		{
			/// implementation
		});

		ServiceRunner<ExampleService3>.Run(config =>
		{
			/// implementation
		});
	}
}
```

Is this implementation possible or best practice?
If not, what best practice should I use?

**Comment by nefcanto** [comment]
I also need this. I need to be able to run two different services in one host. But the first `ServiceRunner<ExampleService>.Run` doesn't return and the second service never gets a chance to run.
