### ISSUE TITLE
Service did not respond to the start or control request in a timely fashion

### ISSUE THREAD

**Issue by kharlamov** [PeterKottas/DotNetCore.WindowsService#13]
I am having issues starting my service on Windows Server 2008 R2.

Installed it via 
`dotnet .\MyWindowsServiceApplication.dll action:install name:MyWindowsServiceApplication displayName:MyWindowsServiceApplication description:"My windows service application."`

And it shows up, when i try to start it I instantly get `Error 1053 service did not respond to the start or control request in a timely fashion`

When I run in manually through powershell via "dotnet .\MyWindowsServiceApplication.dll action:start" I get the following error through my logging around the `ServiceRunner.Run`:

`
2017-03-23 18:51:16.1887 ERROR Program - System.InvalidOperationException: Cannot start service MyWindowsServiceApplication on computer '.'. ---> System.ComponentModel.Win32Exception: The service did not respond to the start or control request in a timely fashion
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Start(String[] args)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.StartService(HostConfiguration`1 config, ServiceController sc)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.ConfigureService(HostConfiguration`1 config)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.Run(Action`1 runAction)`

I can't tell what is going on as I get no other exception anywhere, any ideas? 

I have managed to get this running locally on my computer which is the annoying part, just not on the server.

**Comment by PeterKottas** [comment]
Hey mate. 2 things come to mind afk. Try to omit ".\" when calling the service. Second thing to try would be running cmd/powershell as administrator. If that doesn't help, give this a read https://github.com/PeterKottas/DotNetCore.WindowsService/issues/12  . Tou might find some good points there. If nothing helps, I'll get back to to u tomorrow ;-)

**Comment by kharlamov** [comment]
Yeah tried both of this things with no luck, I have simplified my app down to this, and again working locally not on the server:


```
        public static void Main(string[] args)
        {
            LogManager.Configuration = new XmlLoggingConfiguration(
                Path.Combine(AppContext.BaseDirectory, "NLog.config"), true);
            var logger = LogManager.GetCurrentClassLogger();

            Console.WriteLine("I am outputing.");
            ServiceRunner<MyWindowsServiceApplicationService>.Run(config =>
            {
                config.SetName("MyWindowsServiceApplication");
                var name = config.GetDefaultName();

                config.Service(serviceConfig =>
                {
                    serviceConfig.ServiceFactory(extraArguments => new MyWindowsServiceApplicationService());
                    Console.WriteLine("I am outputing.");

                    serviceConfig.OnStart((service, extraParams) =>
                    {
                        Console.WriteLine("I am not outputing.");
                    });

                    serviceConfig.OnStop(service =>
                    {
                    });

                    serviceConfig.OnError(e =>
                    {
                        Console.WriteLine(e);
                        logger.Error(e);
                    });

                });
            });
        }
```

```
    public class MyWindowsServiceApplicationService : IMicroService
    {

        public void Start()
        {

        }

        public void Stop()
        {
        }
    }
```

**Comment by PeterKottas** [comment]
I looks kinda similar to that issue I've send you previously. Try to get the int that the run method returns. It should be 0 if it works properly.

**Comment by PeterKottas** [comment]
Also get the app path this way : PlatformServices.Default.Application.ApplicationBasePath . That's what I use so it's worth trying.

**Comment by kharlamov** [comment]
Updated the path, the run method is returning a -1.

**Comment by kharlamov** [comment]
Amazing what a good nights sleep can do, I figured it out in my nightmares. The problem is the path and the command that gets generated. 

Locally the command thats getting setup for the service is  `C:\Program Files\dotnet\dotnet.exe C:\Projects\MyWindowsServiceApplication\MyWindowsServiceApplication\bin\Debug\netcoreapp1.1\MyWindowsServiceApplication.dll action:run` Notice no spaces to the DLL. 

However on the server `C:\Program Files\dotnet\dotnet.exe C:\Program Files\My Windows Service\MyWindowsServiceApplication.dll action:run` has spaces in `Program Files` and `My Windows Service` which is making them invalid. 

Is there anyway to fix this, could we wrap the second parameter in quotes through `dotnet .\MyWindowsServiceApplication.dll action:install` I am not sure if thats valid?

**Comment by PeterKottas** [comment]
Hi Andrew, don't worry, you're not spamming at all. On the contrary, good catch about the error! I'll make the change now and will upload new version so that you can give it a try. Will let you know once it's done

**Comment by PeterKottas** [comment]
Ok that's done and uploaded in [v1.0.17](https://github.com/PeterKottas/DotNetCore.WindowsService/releases/tag/v1.0.17) Let me know if it helps ;)

**Comment by kharlamov** [comment]
Just tested up on the server works perfect, thank you so much :+1:

**Comment by PeterKottas** [comment]
Awesome, glad we fixed it mate. Thanks for making this lib better! Spread the work and let me know if you need anything else ;)
