### ISSUE TITLE
Install using powershell

### ISSUE THREAD

**Issue by kmcgain** [PeterKottas/DotNetCore.WindowsService#14]
It would be nice to be able to run:
New-Service -BinaryPathName $serviceExeFullPath -Name $serviceName -DisplayName $serviceName -StartupType Automatic
from powershell. This is supported by Topshelf.
The action options work well but this different interface causes issues when deploying different services, we need to know which windows service library was used.

If I use New-Service to install the service using this library the service will fail to start up.

**Comment by PeterKottas** [comment]
Hi there, this doesn't sound like something that would be easily doable. The way this works is very different from topshelf. This is quite a small lib currently focused on functionality and features over specific syntax when running the service. It would obviously be doable and if you want, feel free to fork it up and I'll be happy to review changes, but atm, this is probably not something I would look into. You will still be able to deploy using powershell but yeah, the api is different to topshelf so your deploy scripts would have to handle that atm.

**Comment by andymac4182** [comment]
@kmcgain I have this working with `sc.exe` using a standalone app. I am sure you could get the same working with `New-Service`

**Comment by kmcgain** [comment]
Hi, thanks for the feedback. It turns out it does work fine using New-Service.
I needed to specify -BinaryPathName "path_to_exe action:run"

By missing the action:run in bin path it fails to run (presumably running the console app and not providing windows service callbacks).

Is it worth updating the doc page with an example of this?

**Comment by andymac4182** [comment]
@kmcgain It would be worth providing a PR to the README covering this personally. It was a little frustrating to find when I did this for myself.

**Comment by kmcgain** [comment]
https://github.com/PeterKottas/DotNetCore.WindowsService/pull/18

**Comment by PeterKottas** [comment]
Hi gents, apologies, been a busy week, I only got to this now. Glad it worked for you guys after all! Good job helping out @andymac4182 and thanks for the pr @kmcgain .

**Comment by gitfortee** [comment]
Hello there. I need to deploy a windows service to an 2008 R2 machine. 

I need to specify a user account and password for the service to run using. 

This is the powershell script. 

New-Service -Name "MyServiceName" -BinaryPathName ".\Consoleapp.dll action:run username:domain\username password:passwordstring" -StartupType Automatic 

But i get 

Windows could not start the CourierReports service on Local Computer.
Error 2: The system cannot find the file specified. 

I looked up the service properties to see the path to executable has ".\Consoleapp.dll action:run username:domain\username password:passwordstring" 

so how should my powershell command look like.?

**Comment by gitfortee** [comment]
@PeterKottas  Ok. I figured out the right script that i can use to install the service. But now i get an error like this.. and i do not see any logs. any idea what is going wrong..? 

A timeout was reached (30000 milliseconds) while waiting for the "MyServiceName" service to connect.
