### ISSUE TITLE
Is it possible to target netcoreapp1.0?

### ISSUE THREAD

**Issue by andymac4182** [PeterKottas/DotNetCore.WindowsService#15]
I have a netcoreapp1.0 which runs on AWS Lambda and also running on premise kit as well. It would be great if this could target 1.0 as well.

Any reason this project can't target `netstandard1.6` or lower?

**Comment by PeterKottas** [comment]
Hi @andymac4182, nope, no reason per say (although I didn't try so there might be surprises), it just isn't configured. Interesting, I didn't even know you can run dot net core on lambda. Do you find it working okay?

**Comment by andymac4182** [comment]
It has a slower start up time compared with nodejs but once the container is warm it has good performance. We haven't got anything in production yet which is what I am working on at the moment.

**Comment by PeterKottas** [comment]
Nice one, I might give it a shot as well, although in general I prefer docker will see how it goes. Anyways, it should be pretty straight forward to support net standard 1.6, I think I can make that happen this evening. Will let you know once it's done.

**Comment by andymac4182** [comment]
@PeterKottas I have submitted a PR that compiles. I just haven't had time to test it in the sample app yet.

**Comment by PeterKottas** [comment]
Hey mate, please check out if https://www.nuget.org/packages/PeterKottas.DotNetCore.WindowsService/1.0.18 will be more to tour liking :) It supports netcoreapp1.0 and netcoreapp1.1, hope it enables you to continue working. Let me know if it helps

**Comment by andymac4182** [comment]
Thanks!! I just finished updating my app to use this and it is working perfectly. (Once I worked out that `Directory.GetCurrentDirectory()` for a service is `C:\windows\system32\`) 🎉
