### ISSUE TITLE
Having trouble running with action:run

### ISSUE THREAD

**Issue by btompkins** [PeterKottas/DotNetCore.WindowsService#19]
When I attempt to start my service without any parameters, it runs fine, but when I use action:run I get the following errors:

PS C:\Projects\pts.betasystems\src\PTS.BetaSystems.Web\bin\Release\PublishOutput> dotnet .\PTS.BetaSystems.Web.dll action:run

Service PTS.BetaSystems.Web.Program+ExampleService errored with exception : The service process could not connect to the service controller

I get this error even if I comment out any of my own code in my start method.

Here's my project.json file: 

{
    "userSecretsId": "aspnet-WebApplication1-f8dd4d00-7f76-4595-97e6-5aa03aa0aa63",

  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },
    "Microsoft.AspNetCore.Mvc": "1.1.0",
    "Microsoft.AspNetCore.Routing": "1.1.0",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.1.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.1.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.Extensions.Logging.Console": "1.1.0",
    "Microsoft.Extensions.Logging.Debug": "1.1.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.1.0",
    "Microsoft.AspNetCore.StaticFiles": "1.1.0",
    "Microsoft.AspNetCore.SpaServices": "1.0.0-beta-000019",
    "Microsoft.AspNetCore.Antiforgery": "1.1.0",
    "Microsoft.AspNetCore.Diagnostics": "1.1.0",
    "Microsoft.AspNetCore.Authentication.Cookies": "1.1.0",
    "Microsoft.AspNetCore.Authentication": "1.1.0",
    "NLog.Extensions.Logging": "1.0.0-rtm-beta2",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.Extensions.Configuration.UserSecrets": "1.1.0",
    "Microsoft.Extensions.Logging": "1.1.0-*",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0",
    "Microsoft.VisualStudio.Web.CodeGeneration.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.VisualStudio.Web.CodeGenerators.Mvc": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Swashbuckle.AspNetCore": "1.0.0-rc1",
    "Hangfire": "1.6.12",
    "NLog.Web.AspNetCore": "4.3.1",
    "Hangfire.MemoryStorage": "1.5.0"
  },

  "tools": {
  "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.1.0-preview4-final"
  },

    "frameworks": {
      "netcoreapp1.0": {
        "imports": [
          "dotnet5.6",
          "portable-net45+win8"
        ]
      }
    },

    "buildOptions": {
      "emitEntryPoint": true,
      "preserveCompilationContext": true
    },

    "runtimeOptions": {
      "configProperties": {
        "System.GC.Server": true
      }
    },

    "publishOptions": {
      "include": [
        "wwwroot",
        "web.config",
        "Views",
        "nlog.config",
        "devices.json"

      ]
    },

    "scripts": {
      "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
    }
  }

**Comment by PeterKottas** [comment]
Hi there. Luckilly this should be very easy to fix. All you have to do is call action:install. That is the one you should you to set this up as a windows service. You also have action:uninstall,stop,start which allows you to work with an existing service. I often suggest to people who are setting these up for the first time to create code that writes to file. Some sort of logger. That way you can easily see if everything is working. As a side note, when working with dot net core, I really suggest to move to vs 2017. They got rid of project.json for example. Also all of the future release will be vs 2017 oriented. Just something to think about :) let me know if action install helped. Btw, action:run is more of an internal thing. To run it as a console app, just run it as you normally would without any params.

**Comment by btompkins** [comment]
Thanks Peter, I was having trouble running after I called action:install.  That's when I saw the action:run being passed to the command line.  Tried that and figured this error was the reason my service was not responding. I will implement logging around startup to see if there's some other problem.

**Comment by PeterKottas** [comment]
Yep that should help you out. Worst case pull down the code. There's an example there which should work

**Comment by btompkins** [comment]
Peter, 

When I try to log, running as a service, the following code doesn't write a file, or throw any errors, it's like it's not even entering main. 

When I run from the command line, everything works as expected.  

  public class Program
    {
        public static void Main(string[] args)
        {
            ServiceRunner<KestrelHostService>.Run(config =>
            {
                
                var name = config.GetDefaultName();
                config.Service(serviceConfig =>
                {
                    serviceConfig.ServiceFactory((extraArguments) => new KestrelHostService());

                    serviceConfig.OnStart((service, extraParams) =>
                    {
                        File.AppendAllText("startup.log", $"Service {name} started");
                        service.Start();
                    });

                    serviceConfig.OnStop(service =>
                    {
                        File.AppendAllText("startup.log", $"Service {name} stopped");
                        service.Stop();
                    });

                    serviceConfig.OnError(e =>
                    {
                      File.AppendAllText("startup.log", $"Service {name} errored with exception : {e.Message}");
                    });
                });
            });

            
        }
    }


    public class KestrelHostService : IMicroService
    {
        public void Start()
        {

            var host = new WebHostBuilder()
                .UseKestrel()
                .UseContentRoot(Directory.GetCurrentDirectory())
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }

        public void Stop()
        {
            File.AppendAllText("startup.log", "Service stopped");
        }

**Comment by PeterKottas** [comment]
Hey mate, just came back from a long holiday, that's the reason I haven't replied sooner. Will have a chance to give my attention to github again. From what you've written, it seems you might be over complicating it. Basically what you are trying to do is host a website as a service. This lib was meant for hosting microservices where you don't have the luxury of having the WebHostBuilder. Please take a look at this as it might help you.  https://docs.microsoft.com/en-us/aspnet/core/hosting/windows-service
If you are looking at building a microservice, then this lib is definitely for you and best way to start is the example provided in the repo. Happy coding ;) And sorry for the late reply, holidays were great though :D

**Comment by webchetan** [comment]
Can I run this service as a timely fashion. Like every 10 minutes?

Also I am not able to open the project in Visual Studio 2015. It always says cannot load project.

> Can we have the project migrate to the latest netcoreapp1.1 with .csproj based tooling instead of the legacy project.json.?

Thank you!

**Comment by webchetan** [comment]
![image](https://cloud.githubusercontent.com/assets/597338/26508335/6075c792-4222-11e7-9612-fd965b9a9103.png)

This is the error I am getting. Please advise.

**Comment by PeterKottas** [comment]
Hey @webchetan hope all is well. In general it's better to open a new issue. However since it's already here, I'll try to answer and if we get into bigger discussion that can be interesting for other, we'll move it to a new one. 
So to answer the first question, yes it's possible to run a timer inside the service. In fact, there's also an example and a built in timer. But as long as you place any timer in start method it would just work. It's just a code being executed so any c# constructs are valid. 

Second question, for development, we only support latest vs2017 it's actually csproj based. project.json was removed from this couple months ago. Vs2017 is available for free (community edition ) I recommend it very much for working with .net core. Like you can see [here](https://github.com/PeterKottas/DotNetCore.WindowsService/blob/master/Source/PeterKottas.DotNetCore.WindowsService/PeterKottas.DotNetCore.WindowsService.nuspec), it supports both 1.0 and 1.1 of netcoreapp. Also [here ](https://github.com/PeterKottas/DotNetCore.WindowsService/tree/master/Source/PeterKottas.DotNetCore.WindowsService) you see csproj so no project.json (that was previously used in vs2015)
Hope that helps ;)

**Comment by ctschappat** [comment]
Peter,

 I am experiencing the same issue that @btompkins reported:
"When I try to log, running as a service, the following code doesn't write a file, or throw any errors, it's like it's not even entering main.
When I run from the command line, everything works as expected."

I am not using the Kestrel WebHosting pieces. I have three services I have written and am trying to make use of your library. All three behave in the same manner. Have you had a chance to dig deeper into this?

Thanks!

**Comment by PeterKottas** [comment]
Hi there @ctschappat , could you please open a new issue for this? This one is really starting to be cluttered.

**Comment by webchetan** [comment]
@PeterKottas Thank you! Appreciate it. Should it be ok to install VS 2017 Community Edition with VS 2015 Professional already installed on the machine?

Thanks again.

**Comment by PeterKottas** [comment]
It will be okay, no worries about that. One small issue though. Or behavior if you will. Installing Vs2017 will overwrite the path variable pointing to dot net core sdk. That means that running in vs2015 will stop working unless you fix it. Quick google search will show you how. TBH, I recommend not doing dot net core in 2015 at all. Yes you can, but vs2017 was just made for it and receives way more support. So if at all possible, I recommend for it to become your go to IDE for dot net core

**Comment by webchetan** [comment]
@PeterKottas Thank you! Much appreciate it.
