### ISSUE TITLE
Service name isn't set when calling config.SetName

### ISSUE THREAD

**Issue by Yantrio** [PeterKottas/DotNetCore.WindowsService#2]
https://github.com/PeterKottas/DotNetCore.WindowsService/blob/8f7be640be36c45c1f39f775f0460c6a89d9989a/Source/PeterKottas.DotNetCore.WindowsService/HostConfigurator.cs#L20

this line of code is stopping us setting the name inside ServiceRunner<T>.Run because the name was already set :(. Is there any quick way I can get around this?

**Comment by PeterKottas** [comment]
Sorry, closed it by mistake right away :) This should solve your problem @Yantrio Let me know if it works. I've pushed it to nuget. The version for this is 1.0.7. Hope that helps ;)

**Comment by PeterKottas** [comment]
I've refactored some stuff around how the service installs as well just so that you know. Basically now if you install and it finds it installed already, it will reinstall it automatically so you don't have to call uninstall/install all the time.

**Comment by Yantrio** [comment]
That's perfect, thanks :)

**Comment by Yantrio** [comment]
Did you upload the correct nuget package? this is what I have, it only seems to have 1 method with the force bool.

![screen shot 2017-01-13 at 14 17 55](https://cloud.githubusercontent.com/assets/237469/21932976/2a6a2cb4-d99b-11e6-9f40-f9965994b919.png)

**Comment by Yantrio** [comment]
Perfect, thanks :)
