### ISSUE TITLE
IOEccption with example code

### ISSUE THREAD

**Issue by KantJoe** [PeterKottas/DotNetCore.WindowsService#22]
```

Timers.Start("Poller", 1000, () =>
            {
                File.AppendAllText(fileName, string.Format("Polling at {0}\n", DateTime.Now.ToString("o")));
            });
Console.WriteLine("I started");
File.AppendAllText(fileName, "Started\n");

```
Timers.Start and FileAppendAllText in different process,while one of then create /begin write,the another process may throw an exception of 'The process cannot access the file 'xxx\yyy\log.txt' because it is being used by another process'.
i think user-code with different namespace makes it happend.

**Comment by PeterKottas** [comment]
Hey mate, I hear your pain but this is a standard thing in dot net. This is something you have to take care of your own. There are all sorts of locks, timeouts that you can employ to fix your problem. Same thing happens with all sorts of loggers (log4net for example). Some bright people had to sit down at some point and introduce some mechanism to make this happen. Usual approach is to create a buffer of some sort. That acts like a singleton and you write in that, and then you dump it out to a file periodically or based on it's length and some other constraints. This is not something that is specific for this lib so if this answer suffice, feel free to close it.
