### ISSUE TITLE
Trouble Running as a Service (action:run)

### ISSUE THREAD

**Issue by ctschappat** [PeterKottas/DotNetCore.WindowsService#23]
Hi Peter,

I have three services I have written that make use of your library. When I deploy any of them - deployed to Windows 10, Windows Server 2012 R2 and Windows Server 2016 - the service installs fine but does nothing when it runs - it only ever enters the Main method once right after install and never again.

If I try to run it at the console with the "action:run" parameter it gives me the following error:

Service [my service name] errored with exception : The service process could not connect to the service controller

If I run it from the console without the action parameter, it runs fine.

Thoughts?
Thanks!

**Comment by PeterKottas** [comment]
Good morning :) Hope you are well! It's not easy for me to understand what's going on from what you've written. Is it a website you are trying to host this was or is it a true microservice? Because remember, this package is used for microservices, website can be hosted easily with .net core. If that's the case, just follow this : https://docs.microsoft.com/en-us/aspnet/core/hosting/windows-service
Speak soon ;)

**Comment by ctschappat** [comment]
Good Morning,
No, I am not trying to run it as website. This is a true microservice.
I did, however trace the problem through to the DasMuli code and not yours. So, I will be opening an issue over there, instead.
Thanks!

**Comment by bjcull** [comment]
Having the same problem. Everything works except action:run. It's just a regular console application.

**Comment by PeterKottas** [comment]
Cheers @ctschappat hope it's sorted, let me know if you need my assistance ;)

**Comment by PeterKottas** [comment]
@bjcull Hey mate, avoid using action:run that's an internal thing. Go for action:install if you want to install the service, action:start / action:stop to control it. And so on. If you want to run as console app, just run it as you normally would (without any action)

**Comment by bjcull** [comment]
The only reason I tried using action:run was to try and figure out what's happening. Install works, and the service starts correctly, I think, I can't tell. But it doesn't appear to actually do anything.

Stopping also works successfully.

If I just run the service without arguments, everything works fine. Any ideas as to what I might be missing?

**Comment by PeterKottas** [comment]
Ok, no worries @bjcull we'll look into that. Create a new issue please though. Easier to track stuff and also to point people to the right place if they see these problems later. Thanks man
