### ISSUE TITLE
Not able to start a .net core service

### ISSUE THREAD

**Issue by imran2489** [PeterKottas/DotNetCore.WindowsService#24]
Hi Peter, 

Nice work. 

Is it possible to start a .net core project from Start() , like this,

var host = new WebHostBuilder()
                    .UseKestrel(options => { options.AddServerHeader = false; })
                    .UseContentRoot(Directory.GetCurrentDirectory())
                    .UseUrls("http://*:5000")
                    .UseIISIntegration()
                    .UseStartup<Startup>()
                    .Build();

            host.Run();

I tried this, a service is created . But unfortunately if i try accessing http://localhost:5000 it didnt work. 

I am struck on it and any help is really appreciated.

**Comment by PeterKottas** [comment]
Hello there mate! From what you've written, it seems you might be over complicating it. Basically what you are trying to do is host a website as a service. This lib was meant for hosting microservices where you don't have the luxury of having the WebHostBuilder. Please take a look at this as it might help you. https://docs.microsoft.com/en-us/aspnet/core/hosting/windows-service
If you are looking at building a microservice, then this lib is definitely for you and best way to start is the example provided in the repo. Happy coding ;) (feel free to open the issue again but I am 99% percent sure this will suffice for the problem you are trying to solve)
