### ISSUE TITLE
Special Characters In Password Not Working

### ISSUE THREAD

**Issue by jkruer01** [PeterKottas/DotNetCore.WindowsService#25]
I created a service and deployed it to the server.

I ran the following command:
`.\myApp.exe username:MyUsername password:MyPassword!$?# action:install`

I received the following errors:

> The service did not start due to a logon failure

When I open the Windows Services Manager the service is installed with the correct username but it is not running.  I right click > Properties > LogOn > Copy And Paste Password from command line, everything works correctly and the service starts.

Are special characters such as !, $, ?, and # not supported in the password field?

**Comment by PeterKottas** [comment]
Thanks man, well spotted! This one will actually probably go to https://github.com/PeterKottas/DotNetCore.CmdArgParser That's the lib responsible for parsing arguments. I'll take a look and let you know.

**Comment by PeterKottas** [comment]
Ok I've looked into it and it works for me no problem. 
I guess you didn't want to hear this :P
What I suggest is to clone this repo, go into example and try it there.
Also put something like 
serviceConfig.OnError(e =>
                    {
                        Console.WriteLine("Service {0} errored with exception : {1}", name, e.Message);
                        Console.ReadLine();
                    });
In the config to make sure to catch the actual error if there is any.
