### ISSUE TITLE
Dependency Injection on Ctor of Service

### ISSUE THREAD

**Issue by xVishera** [PeterKottas/DotNetCore.WindowsService#26]
Hello !

I'm trying to use your lib to create a XML import service, but I have to do dependency injection on my service.

The problem is, I can't call

`serviceConfig.ServiceFactory((extraArguments) =>
                    {
                        return new CustomerXmlService();
                    });`
because CustomerXmlService have a lots of ctor reqs

Any ideas of a workaround ?

**Comment by dmitry-pavlov** [comment]
@xVishera as far as I understand your CustomerXmlService class just need to implement IMicroService interface with 2 methods - Start() and Stop(). And you can pass to new CustomerXmlService(...) whatever you need. What is the issue here? 

```
var myParam = ...
serviceConfig.ServiceFactory((extraArguments) => { return new CustomerXmlService(myParam); });
```

**Comment by xVishera** [comment]
> var services = new ServiceCollection();
services.AddTransient<IYourInterface, YourImplementation>();
...
var serviceProvider = services.BuildServiceProvider();
var yourService = serviceProvider.GetService<IYourInterface>();

This is what I need, inject manually the service interface without a constructor. Thanks.

**Comment by PeterKottas** [comment]
Thanks for helping @dmitry-pavlov , I wouldn't say it better myself ;) Hope everything will work no probs now @xVishera
