### ISSUE TITLE
update readme example to csproj

### ISSUE THREAD

**Issue by PaluMacil** [PeterKottas/DotNetCore.WindowsService#27]
Would you be open to updating the readme example to csproj? I see your example project does this already, and if you only have time to reply here, I could probably make a pull request.

**Comment by PeterKottas** [comment]
Apologies for a very late reply, I left my current job and starting a new company so you can probably imagine it's been quite crazy recently :D I am going to do this now.

**Comment by PeterKottas** [comment]
Taken care of in https://github.com/PeterKottas/DotNetCore.WindowsService/releases/tag/v1.0.20 .
