### ISSUE TITLE
.net CLI template

### ISSUE THREAD

**Issue by PaluMacil** [PeterKottas/DotNetCore.WindowsService#28]
Would you be interested in maintaining a CLI template called "winservice" or something along those lines? This would probably require maintenance of a project and Nuget package, but I think it would get used a lot!

Reference: https://github.com/dotnet/templating

**Comment by PeterKottas** [comment]
Same as the previous issue you opened, was busy but more than happy to do that, sounds like it can be useful to the community. In fact, I think with 100+ stars, the time has come to look into this again and add some new features. Will do the template as well

**Comment by PeterKottas** [comment]
Taken care of in https://github.com/PeterKottas/DotNetCore.WindowsService/releases/tag/v1.0.20 .
