### ISSUE TITLE
Hello, find a question in action:install 

### ISSUE THREAD

**Issue by MikeDGitHub** [PeterKottas/DotNetCore.WindowsService#33]
dotnet LoggerService.dll action:install
Service LoggerService.ExampleService errored with exception : The service did not respond in time to initiate or control the request.

dotnet LoggerService.dll action:start
Service LoggerService.ExampleService errored with exception : Cannot start service LoggerService.ExampleService on computer '.'.

namespace LoggerService
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.OutputEncoding = Encoding.UTF8;
            ServiceRunner<ExampleService>.Run(config =>
            {
                var name = config.GetDefaultName();
                config.Service(serviceConfig =>
                {
                    serviceConfig.ServiceFactory((list, extraArguments) =>
                    {
                        return new ExampleService();
                    });
                    serviceConfig.OnStart((service, extraArguments) =>
                    {
                        Console.WriteLine("Service {0} started", name);
                        service.Start();
                    });

                    serviceConfig.OnStop(service =>
                    {
                        Console.WriteLine("Service {0} stopped", name);
                        service.Stop();
                    });

                    serviceConfig.OnError(e =>
                    {
                        Console.WriteLine("Service {0} errored with exception : {1}", name, e.Message);
                    });
                });
                config.SetDescription($"{name},Description");
                config.SetDisplayName($"{name},DisplayName");
                config.SetName(name);
            });
            Console.ReadLine();
        }
    }
    public class ExampleService : IMicroService
    {
        readonly EventConsumer _eventConsumer = KafkaConsumer.Consumer(Guid.NewGuid().ToString(), new string[] { "LoggerTopic" });
        public void Start()
        {
            KafkaConsumer.Start(_eventConsumer);
            Console.WriteLine("I started");
        }

        public void Stop()
        {
            KafkaConsumer.Stop(_eventConsumer);
            Console.WriteLine("I stopped");
        }
    }
}

**Comment by bedwar2** [comment]
I had a similar issue, and I have a feeling it is in KafkaConsumer.  If KafkaConsumer is trying to read or write a file from the application execution path, depending on how you are trying to get that path, could be the issue.  I was using "Environment" initially.  I had to change to use PlatformServices.Default.Application.ApplicationBasePath

**Comment by PeterKottas** [comment]
Oh yeah, that rings a bell! I think it's in the readme. You should always use PlatformServices.Default.Application.ApplicationBasePath with this

**Comment by MikeDGitHub** [comment]
Thank you
