### ISSUE TITLE
Uninstall error missing dll api-ms-win-service-core-l1-1-1.dll

### ISSUE THREAD

**Issue by bedwar2** [PeterKottas/DotNetCore.WindowsService#34]
Hello Peter, thank you very much for creating this.  In executing dotnet run action:install everything worked fine.  However when I do action:uninstall I am getting: 
Service eAchieveBatchReports.EAchieveReportService errored with exception: Unable to load DLL 'api-ms-win-service-core-l1-1-1.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) 
Stack Trace:    at Interop.mincore.EnumServicesStatusEx(IntPtr databaseHandle, I
nt32 infolevel, Int32 serviceType, Int32 serviceState, IntPtr status, Int32 size
, Int32& bytesNeeded, Int32& servicesReturned, Int32& resumeHandle, String group
)
   at System.ServiceProcess.ServiceController.GenerateNames()
   at System.ServiceProcess.ServiceController.GetServiceHandle(Int32 desiredAcce
ss)
   at System.ServiceProcess.ServiceController.GenerateStatus()
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.Uninstall(HostConfig
uration`1 config, ServiceController sc)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.UsingServiceControll
er(HostConfiguration`1 config, Action`2 action)
   at PeterKottas.DotNetCore.WindowsService.ServiceRunner`1.Run(Action`1 runActi
on)

Do you know where I can find this missing DLL? 

Also, how would I later deploy this to a production server?  Not an issue, question, sorry.

**Comment by bedwar2** [comment]
Note that I was able to uninstall using sc.exe delete "servicename" 

For my question at the bottom, would this work when ready to put on a production server? 
sc.exe create MyService DisplayName= "My Service" binpath= "C:\Program Files\dotnet\dotnet.exe C:\path\to\MyService.dll --run-as-service"

**Comment by PeterKottas** [comment]
Hi there, nope this is not how it's intended to work. You call your binary directly. Either through dotnet.exe or if self-contained, via your executable. Therefore remove all sc.exe and all should work. 
You can use whatever you choose to deploy to production. I've used octopus before. But this is basically a few lines powershell script if you want to keep it simple.

**Comment by bedwar2** [comment]
Ok thanks for the reply.  My question now is why the "action:install" worked just fine but the "action:uninstall" resulted in the error you see in the original question.  I couldn't uninstall the service until I used SC.EXE.

The sc.exe command was in dasMulli's documentation which is why I thought it may work in this case too.

**Comment by PeterKottas** [comment]
Do you run the command prompt as administrator?

**Comment by bedwar2** [comment]
Yes and it installs great, can start and stop the service.  Just get the missing dll when trying to uninstall.

**Comment by PeterKottas** [comment]
That's really strange. I am thinking it would be best if you clone this repo and try the example. That can pinpoint the problem better as this repo works for plenty of people no problem.

**Comment by bedwar2** [comment]
hi Peter, so the action:uninstall and action:install worked fine when I deployed to the server.  Not sure why just the uninstall didn't work on the Windows 7 VM but not too concerned since the fallback using SC.EXE worked there.   Again, thanks, what a great product!

**Comment by PeterKottas** [comment]
Awesome! Glad it works now. It might be some weird antivirus sorcery. Who knows. But as long as live works ;)

**Comment by brent-williams** [comment]
Identical experience here, install ok uninstall fails w/ given dll.  .NET Core 2.0 on Windows 7 x64.
