### ISSUE TITLE
Severity Code Description Project File Line Suppression State Error  Could not install package 'PeterKottas.DotNetCore.WindowsService 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author. 

### ISSUE THREAD

**Issue by rajamanr** [PeterKottas/DotNetCore.WindowsService#37]
we are trying to make a console application written in DOTNET CORE function as a service. This used to work in previous dotnet versions. Currently, when we create a service using sc create, the service gets created. But it goes into a stopped state. When we try and start it, we get the 1053 error that it didn't start up in a timely fashion. 

After a lot of looking around, I came across your NUGET that helps convert the code into a service. I am trying to include your NUGET Package via 
`Install-Package PeterKottas.DotNetCore.WindowsService `
But we are getting the error 
`Severity Code Description Project File Line Suppression State
Error  Could not install package 'PeterKottas.DotNetCore.WindowsService 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

My questions are 
1. Why are we facing this issue with Windows services
2. How do we overcome the error to incorporate into 4.6.1

**Comment by PeterKottas** [comment]
Hi, you are not writing in full .netcore sdk. You are using .NETFramework,Version=v4.6.1. This lib is written for dot net core, you need to switch to full framework and then you can use it. If you are using old .net framework, you can use something like Topshelf. Cheers

**Comment by rajamanr** [comment]
you are right, we are using 4.6.1 as well as dot net core elements
how does one go about making the service? I did go through top shelf. I am not very clear as to why it is not working on its own, and do we just install Topshelf as a nuget like your package?

**Comment by PeterKottas** [comment]
It should be easy to find docs around the internet. The api is pretty similar to mine as I got the inspiration there. I can't really give you walk-through on that but as I've said it should be easy to obtain on google or elsewhere.

**Comment by rajamanr** [comment]
Noted. thank you for everything

**Comment by PeterKottas** [comment]
No probs :) Good luck!
