### ISSUE TITLE
Installing/Publishing

### ISSUE THREAD

**Issue by xVishera** [PeterKottas/DotNetCore.WindowsService#39]
Hello, I'm trying to publish/install my service but I'm facing some problems.

When I run it directly from VS2017 it works fine.

When I try to "publish" I recieve only errors.

When I rebuild in "Release" and try to install from a powershell (admin) using the command
(The rebuild doesn't create a .exe"

New-Service -Name MyService.TesteService -BinaryPathName "C:\Users\Luk\Desktop\MyCustomService action:run" -StartupType Automatic

The service install but stoped, When I try to run I receive an error of "Access declined"

appsettings.json

```
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Warning"
    }
  },

  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": { "Microsoft.NETCore.App": { "version": "1.1.0" } },
      "imports": "dnxcore50"
    },
    "dnx451": {
    },
    "imports": [ "dotnet5.6", "dnxcore50", "portable-net45+win8" ]
  },

  "runtimes": {
    "win81-x64": {},
    "win7-x64": {},
    "win10-x64": {},
    "win10-x86": {}
  }
```

Is there anything I should do before it ?

----- EDITED

Ok, managed to get an .exe of my service.

If I run the exe, the service executes correct.

When I try to run "MyService.exe action:install" it install a service but cant startup, it gives me the following error

Error 1053: The service did not respond to the start or control request in a timely manner.

**Comment by ragnarol** [comment]
I have a similar error and turn out to be the way I was accessing my appsettings.json.

Take into account that the base folder your service will be running from won't be the folder were the assembly is.

In my case I changed:

```
                var configuration = new ConfigurationBuilder()
                    .SetBasePath(Directory.GetCurrentDirectory())
                    .AddJsonFile("appsetings.json", false, false)
                    .Build();
```

For 

```
                var configuration = new ConfigurationBuilder()
                    .AddJsonFile("appsetings.json", false, false)
                    .Build();
```

And worked like a charm

**Comment by xVishera** [comment]
I'm using at the moment

```
            #region appSettings Initialization
            var builder = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
               .AddJsonFile("appsettings.json")
               .AddEnvironmentVariables();
```

I'm compiling right now with 

``` 
var builder = new ConfigurationBuilder()
               .AddJsonFile("appsettings.json")
               .AddEnvironmentVariables();
```

To test.

**Comment by xVishera** [comment]
As you said, worked like a charm

**Comment by ragnarol** [comment]
Yeah, the service is running from "C:\Program Files\dotnet\", i wonder if it would be better to wrap the executable in a cmd and run it as the service.

**Comment by ragnarol** [comment]
I have ended up doing

`Directory.SetCurrentDirectory(PlatformServices.Default.Application.ApplicationBasePath);`

At the start of my process and that seems to make the service behave as I was expecting. I will try to create a pull request to include this in the base service start.

**Comment by gitfortee** [comment]
@ragnarol  could you please help me understand what does Directory.SetCurrentDirectory do in the context of this issue and why it is needed.? 

My code looks like shown below. I have so far _not_ deployed it outside of my dev machine. Can you suggest if the code shown below needs any changes and will it be helpful to put Directory.SetCurrentDirectory as the first instruction in the InitializeConfiguration method? 

```
private static void InitializeConfiguration()
{
	var builder = new ConfigurationBuilder()
	 .SetBasePath(Directory.GetCurrentDirectory())
	.AddJsonFile("appsettings.json");

	Configuration = builder.Build();
}

public static void Main(string[] args)
{
	InitializeConfiguration(); 			
}
```

**Comment by xVishera** [comment]
@gitfortee Just remove ```.SetBasePath(Directory.GetCurrentDirectory())``` 

The SetBasePath helps in dev to specify the path where the engine will find the appsettings, but when you publish it the service "starts" at a differently place, If you call "setbasePath" it cant find the appsettings and timesout.

**Comment by ragnarol** [comment]
Latest version (2.0,1) should handle the path by itself and use the directory were the assembly is located as the base path, no need of setting it manually.

**Comment by gitfortee** [comment]
Thanks.
