### ISSUE TITLE
Deny access

### ISSUE THREAD

**Issue by wangpengxpy** [PeterKottas/DotNetCore.WindowsService#4]
excuse me, I'm using for my .net core project，I'm can't understand how to use  extraArguments

![1](https://cloud.githubusercontent.com/assets/12961992/22240220/114cd9a8-e255-11e6-8140-996b63dc238f.png)

It's right???  but the result is deny access the following
![1](https://cloud.githubusercontent.com/assets/12961992/22240269/50a3fb9a-e255-11e6-9037-8bb2cc2bd9dd.png)

I don't know how to solve ,I hope to get your reply thanks in advance

**Comment by wangpengxpy** [comment]
oh,sorry,I retry install by using [dotnet run action:install] ,It's always deny access

**Comment by PeterKottas** [comment]
Hey mate, extraArguments are in fact "extra arguments" therefore anything that is not recognised by this library as the argument it understands. dotnet run your.dll action:install blabla, extra arguments would contain "blabla". 

That's the first part. For the second part, win services depends a lot on permissions. Try to run cmd as administrator when running your service.

**Comment by wangpengxpy** [comment]
thanks for your reply,I get .
I encounter some problems  at present, to start service  when I run the project in win7-64  with administrator ,it appears 1053 for error code,but in win8.1-64 with administrator,it's successed. Do you have any suggestions for the problem ???
thanks again.

**Comment by PeterKottas** [comment]
Ok so this is more a question for how dot net core works. Basically what you did by listing frameworks (win7-64/win8.1-64 and so on) is tell dot net core to pack all the required libs (dot net core) into your app. That gives you an .exe instead of usual .dll allowing you to run it without dot net core sdk installed. That can be preferable in some cases although I obviously want to make this work with both portable and app run using dotnet.exe. When using frameworks, you need to make sure you build and run the proper version. Therefore 8.1 on windows 8.1 and so on. Double check if the framework matches your version of windows.

**Comment by wangpengxpy** [comment]
use same version both win7-64 and win8.1-64 for .net core app 1.1.0   
Is it possible to lack components in win7-64? the problem troubled me the whole day ,so I don't know where to start

**Comment by PeterKottas** [comment]
What is you windows that you run this on? Win7 ?

**Comment by wangpengxpy** [comment]
It's win7  work in my company but it has some problems above mentioned.  it's win8.1 for my personal notebook,it's no wrong

**Comment by PeterKottas** [comment]
ok so as long as you have a project.json like this:
`{
  ...other stuff...
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.1.0"
        }
      },
      "imports": "dnxcore50"
    }
  },
  "runtimes": {
    "win81-x64": {},
     "win7-x64": {}
  }
}`
and you run appropriate releases (7 on 7 and 8.1 on 8.1) it should work.

**Comment by wangpengxpy** [comment]
yeah,The same as what you said about setting project.json,but it doesn't work in win7

**Comment by PeterKottas** [comment]
Don't have any win7 around me at the moment. Can you please try one thing? Just pull down the code and try to run the example windows service in this repository. You might need to add win7 runtime but that should be the only thing.

**Comment by wangpengxpy** [comment]
ok,I'll provide specific error message to you when I go to work after the Spring Festival(for China)
Nice to meet you and thanks for your help

**Comment by PeterKottas** [comment]
Perfect, thanks. Enjoy the festival :)

**Comment by wangpengxpy** [comment]
（1）When i run as administrator appear the fllowing error 
![default](https://cloud.githubusercontent.com/assets/12961992/22614841/6b3055d2-eac3-11e6-8218-1bcbf4dbf359.png)

（2）When i don't run as administrator appear the fllowing error
![default](https://cloud.githubusercontent.com/assets/12961992/22614842/7457a82c-eac3-11e6-95e7-92aba42d3ced.png)

I find that the error from here
![3](https://cloud.githubusercontent.com/assets/12961992/22614884/f4445dbe-eac3-11e6-974b-ef7bb2babf2b.png)

I don't understand why will appear garbled and where is the error?

**Comment by wangpengxpy** [comment]
It contains project.json run [dotnet run action:install] with command line,It's right?but for what you say is running 【your.dll】,what's the meaning?

**Comment by wangpengxpy** [comment]
the following is my project.json
![1](https://cloud.githubusercontent.com/assets/12961992/22615033/1ae89004-eac7-11e6-8788-b7df6c53cd9e.png)

**Comment by wangpengxpy** [comment]
A little progress has been made at the moment by the fllowing 
【sc create WindowsService DisplayName= "Ihealthinkcare Crawler" binpath= "C:\Program Files\dotnet\dotnet.exe C:\.WindowsService.dll】
But, when I don't start service appear error:
【errorcode 1053：the service did not respond to the start or control request in a timely fashion for win 7】

**Comment by PeterKottas** [comment]
Ok, I see what's going on now. Instead of what you do ... just find your WindowsService.exe and start it as 
`WindowsService.exe action:install` 
No sc create, no dotnet, just start the exe directly. That should do it.

**Comment by wangpengxpy** [comment]
run 【WindowsService.exe action:install】 appear error:
![1](https://cloud.githubusercontent.com/assets/12961992/22616883/200a2306-eaf2-11e6-8f09-cec3a7567a53.png)

**Comment by PeterKottas** [comment]
It just can't find the config file, you should copy it while building. Something like this in project.json should do it.
`"buildOptions": {
    "emitEntryPoint": true,
    "copyToOutput": [
      "appsettings.json"
    ]
  }`

**Comment by wangpengxpy** [comment]
solve the problem but appear the exception continue
![1](https://cloud.githubusercontent.com/assets/12961992/22616983/7adbedbc-eaf4-11e6-839f-239c1d3191b9.png)

**Comment by PeterKottas** [comment]
Hi @wangpengxpy I've release a new version that should fix a couple of problems. Plese try to update and see if it helps

**Comment by wangpengxpy** [comment]
It doesn't work by run your example directly
![1](https://cloud.githubusercontent.com/assets/12961992/22873102/a7fbad5e-f1f8-11e6-9f15-32ffba6116db.png)

**Comment by PeterKottas** [comment]
What does the exception say? I am afraid I can't read Chinese. Oh you know what ... that actually brings me to an idea. Some parts of the code are hard coded string comparisons with English exception messages. Unfortunately that's what windows throws and I didn't find a better way to figure out what's going on. That means that maybe it can't recognize the proper exception and that's what causing the issue. Knowing what the exception says in English might help.
