### ISSUE TITLE
"Time out has expired and the operation has not been completed" with the Example project

### ISSUE THREAD

**Issue by dharmaturtle** [PeterKottas/DotNetCore.WindowsService#42]
Hi!

I read https://github.com/PeterKottas/DotNetCore.WindowsService/issues/8 and tried to get the example project running. I got the following result:

    C:\Users\dharmaturtle\Downloads\DotNetCore.WindowsService-master\Source\PeterKottas.DotNetCore.WindowsService.Example\bin\Debug\netcoreapp2.0>dotnet PeterKottas.DotNetCore.WindowsService.Example.dll action:install
    Successfully registered and started service "PeterKottas.DotNetCore.WindowsService.Example.ExampleService" ("No description")
    C:\Users\dharmaturtle\Downloads\DotNetCore.WindowsService-master\Source\PeterKottas.DotNetCore.WindowsService.Example\bin\Debug\netcoreapp2.0>dotnet PeterKottas.DotNetCore.WindowsService.Example.dll action:start
    Service PeterKottas.DotNetCore.WindowsService.Example.ExampleService errored with exception : Time out has expired and the operation has not been completed.

I am running cmd as admin. Google isn't much help, though I did find [this](https://stackoverflow.com/questions/19775551/time-out-has-expired-and-the-operation-has-not-been-completed-in-service-manager). I extended the timeout to 10 seconds and the same error occurs. There's nothing in the eventlog.

Anyone have any ideas? Thanks!

**Comment by dharmaturtle** [comment]
When I swap out `ExampleService` with `ExampleServiceTimer`, `action:install` and `action:start` work as expected. It doesn't seem to like the exiting of `ExampleService`.

I've also replicated this behavior on a second freshly formatted machine, both Win10x64 Enterprise.

**Comment by PeterKottas** [comment]
Strange one, cause it definitely works for most people. Me included. Do you run "dotnet NameOfService.dll action:install"? Then in the services, does the service appear running? Or it stops right away?

**Comment by dharmaturtle** [comment]
Programs that exit immediately have this error.
