### ISSUE TITLE
Missing events on the library

### ISSUE THREAD

**Issue by HolyOne** [PeterKottas/DotNetCore.WindowsService#43]
OnPause, OnResume , OnInstall, OnUninstall events are needed for this project to be complete

**Comment by PeterKottas** [comment]
Sure that can be beneficial, I don't need these at the moment, however it would be great if you could add them. I am sure others would appreciate it as well!

**Comment by PeterKottas** [comment]
Implemented by https://github.com/PeterKottas/DotNetCore.WindowsService/releases/tag/v2.0.4
