### ISSUE TITLE
Using power shell to install service creates issues.

### ISSUE THREAD

**Issue by gitfortee** [PeterKottas/DotNetCore.WindowsService#44]
Hello, 

I am facing a mix of issues while trying to install the service using power shell. Once the script completes, the service is appearing in the services.msc GUI. but gets into 'stopped' state. this is the output i got as result of the posh script. I made sure to invoke the shell using "Run as Administrator" 

```
PS C:\Apps\ServiceApp> .\install.ps1
service does not exists
installing service

Status   Name               DisplayName
------   ----               -----------
Stopped  ServiceApp... ServiceApp
installation completed
``` 

I am using a service account to run this service. The credentials for the service account are provided in the install.ps1. (Attaching its contents at the end). 

When i tried to 'start' the service manually, I am getting 

`Error 1053: The service did not respond to the start or control request in a timely fashion.` 

Upon examining the 'Event Log', I could see 

```
Faulting module path: C:\windows\system32\KERNELBASE.dll 

Exception code: 0xe0434352
```

Upon further research, it turns out that I have to register for `AppDomain.UnhandledException` event, which i have "no idea" how to do it. Im still on .net core 1.1. 

I tried `Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "logs\\service-stop.txt")` to write files on 'serviceConfig.ServiceFactory', 'serviceConfig.OnStart, OnStop, and OnError' but those files never were written. I hope this indicates something is wrong. 

The "only time" it works is when i used a batch file with the command "`dotnet ServiceApp.dll action:install`" But I have no way to specify the service account to use. And i have to manually go to the servies.msc to change the Logon property of the service. Which is an overkill and more manual intervention every time i need to deploy a new version of the service. 

Having said that, I am looking for a solution to solve the issues mentioned. And here is the contents of the install.ps1 and the code for the service configuration. 

install.ps1
---------- 

```
$serviceName = "ServiceApp"

# verify if the service already exists, and if yes remove it first
if (Get-Service $serviceName -ErrorAction SilentlyContinue)
{
	# using WMI to remove Windows service because PowerShell does not have CmdLet for this
    $serviceToRemove = Get-WmiObject -Class Win32_Service -Filter "name='$serviceName'"
    $serviceToRemove.delete()
    "service removed"
}
else
{
	# just do nothing
    "service does not exists"
}

"installing service"
# creating credentials which can be used to run my windows service
$secpasswd = ConvertTo-SecureString "somepassword" -AsPlainText -Force
$mycreds = New-Object System.Management.Automation.PSCredential ("serviceaccount@domain.com", $secpasswd)
$binaryPath = "C:\Apps\ServiceApp\ServiceApp.Console.dll"
# creating widnows service using all provided parameters
New-Service -name $serviceName -binaryPathName "$binaryPath action:run" -startupType Automatic -credential $mycreds

"installation completed" 
```

Service configuration: 

```
try
{
	ServiceRunner<ServiceApp>.Run(config =>
	{
		config.SetName("ServiceApp");
		config.SetDisplayName("ServiceApp");
		config.SetDescription("ServiceApp");
		config.Service(serviceConfig =>
		{
			serviceConfig.ServiceFactory((extraArguments, controller) =>
			{
				//logger.Information("Initializing service factory");
				var path = Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "logs\\service-init.txt");
				File.WriteAllText(path, "service is initializing");
				return new ServiceApp(serviceProvider.GetService<DeliveriesProcessor>(),
					serviceProvider.GetService<PickupsProcessor>(),
					serviceProvider.GetService<MockedForTestingProcessor>(),                                
					serviceProvider.GetService<ILoggerFactory>().CreateLogger<ServiceApp>(),
					serviceProvider.GetService<IOptions<ServiceOptions>>());
			});

			serviceConfig.OnStart((service, extraParams) =>
			{
				var path = Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "logs\\service-start.txt");
				File.WriteAllText(path, "service is starting");
				//logger.Information("Starting service.. ");
				service.Start();
			});

			serviceConfig.OnStop(service =>
			{
				//logger.Information("Stopping service.. ");
				var path = Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "logs\\service-stop.txt");
				File.WriteAllText(path, "service is stopping");
				service.Stop();
			});

			serviceConfig.OnError(e =>
			{
				//logger.Error(string.Format("An error occurred while running the service: {0}", e.Message));
				//logger.Error(e.StackTrace);
				var path = Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "logs\\service-error.txt");
				File.WriteAllText(path, e.StackTrace);
			});
		
		});
	});
}
catch (Exception ex)
{
	//logger.Error(string.Format("An error occurred while configuring the service. {0}", ex.Message));
	//logger.Error(ex.StackTrace);

        var path = Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "logs\\exception.txt");
        File.WriteAllText(path, ex.StackTrace);
}
```

**Comment by gitfortee** [comment]
@ragnarol @xVishera @kmcgain @andymac4182 @PeterKottas tagging folks hoping they can take a look at the issue.. 

@andymac4182 

> I have this working with sc.exe using a standalone app. I am sure you could get the same working with New-Service 

can you please share the script that worked for you.? were you able to specify a service account while installing the service using sc.exe.?? 

TIA.

**Comment by xVishera** [comment]
@gitfortee Remove "PlatformServices.Default.Application.ApplicationBasePath" from your path.combine and your application should write the logs.

**Comment by gitfortee** [comment]
@xVishera I would also want to specify an user account for the service. when i use "`myservice.exe action:install`" and specify a user name and password, it will appear on the 'Path to executable' property of the service. which i can't allow. 

Meanwhile, removing "`PlatformServices.Default.Application.ApplicationBasePath`" does not still write log files. I expect the files to be created under "`C:\Apps\ServiceApp\logs`" which did not happen.. 

I guess will still need "`PlatformServices.Default.Application.ApplicationBasePath`" such that the "`logs`" folder is created in the path where the "`ServiceApp.dll`" is present. ??

**Comment by gitfortee** [comment]
Meanwhile, i tried using sc.exe but ending up in the same kind of issues. the script looks like below. I put these inside a batch file but the results are the same even when i tried to run each of the commands separately from the command prompt. 

I also made sure to run the command prompt as "Administrator" 

```
sc.exe delete "ServiceApp"

sc.exe create "ServiceApp" binPath= "C:\Apps\ServiceApp\ServiceApp.Console.dll action:run" DisplayName= "ServiceApp" start= auto

sc.exe config "ServiceApp" obj= "domain\serviceaccount" password= "somepassword"
```

**Comment by xVishera** [comment]
@gitfortee If you run the .exe instead of installing, it works ?

**Comment by gitfortee** [comment]
it works perfectly when : 

I used a batch file with the command "dotnet ServiceApp.dll action:install" 

But I also need to specify a service account to use... at this time, I have to manually go to the servies.msc to change the Logon property of the service. Which is an overkill and more manual intervention every time i need to deploy a new version of the service. 

I do not intend to expose the password by using "`dotnet ServiceApp.dll action:install username:<> password:<>`". Since running this command exposes the password to the '`Path to executable`' property of the service.

**Comment by gitfortee** [comment]
@xVishera this is how the "path to executable" looks like "`C:\Program Files\dotnet\dotnet.exe "C:\Apps\ServiceApp\ServiceApp.dll"  action:run`" when i used 

`C:\Apps\ServiceApp> dotnet ServiceApp.dll action:install` 

Notice that the `action:run` is outside the double quotes.. is this still OK?

**Comment by gitfortee** [comment]
I guess your comment on removing the "`PlatformServices.Default.Application.ApplicationBasePath`" **DO** write the logs However I could not find useful information from the error log. 

I also think to check if everything is OK with the service account that i am using. will keep you posted.

**Comment by xVishera** [comment]
@gitfortee It's hard to tell because I never needed to install this way, But I would give a try with 

```
C:\Program Files\dotnet\dotnet.exe "C:\Apps\ServiceApp\ServiceApp.dll action:run""
```

Because "action:run is part of the command to ServiceApp.dll

**Comment by gitfortee** [comment]
@ragnarol @xVishera @kmcgain @andymac4182 @PeterKottas 

Folks, once again.. the issue still persists. there is no way for me to capture a global exception handler in order to get more details about the  
```
Faulting module path: C:\windows\system32\KERNELBASE.dll 
Exception code: 0xe0434352
``` 
looks like when i specify the service account, i am getting into this error. Meanwhile i check the service account, any help that you could provide is valuable. 

thanks.

**Comment by ragnarol** [comment]
hi @gitfortee 

I install the services using the following powershell:

& dotnet $exe action:install name:$serviceName username:$username password:$password

And neither the username or the passowrd get exposed in the Path to Executable.

**Comment by gitfortee** [comment]
@ragnarol thanks for the response.. do you suggest to create an .exe? meaning a self-contained exe.? at present i have a .dll as a framework dependent deployment. I can try creating an .exe and see how it proceeds. 

Also,  the $exe in your power shell command.. should it contain the absolute path to the .exe ? such as `C:\ServiceApp\ServiceApp.exe ?`

**Comment by ragnarol** [comment]
Hi, sorry it's not an exe it is a dll. The powershell variable is called exe be side I copy that bit from another project.

I run the script through octopus deploy so I understand that it runs it from the folder where the DLL is, so no need of using a full path for it.

**Comment by gitfortee** [comment]
Ok. this is what i found out.. the service started working once i upgraded to .net core version 2.0 !!! To recap, even with .net core version 1.1, there was no difficulty in running the application stand-alone or as a service with a "local system" account. The service started to fail only when i configured it to run using a service account..

However, with the same service account and after upgrading my projects and libraries to core version 2.0, the service is working fine.. strange.!! 

For your Ref: https://github.com/PeterKottas/DotNetCore.WindowsService/issues/45#issuecomment-335643337
