### ISSUE TITLE
.net core 2 

### ISSUE THREAD

**Issue by justinteaw** [PeterKottas/DotNetCore.WindowsService#47]
Downloaded the project and built it.  I don't see any exe file being produced.

**Comment by avisonmaher** [comment]
Hey Justin,

I had this issue too. You need to use MSBUILD to publish the project and then you get your .exe file. The simplest way to do this is right clicking the project and then click "Publish", go through the motions and then go to the folder specified in your publish profile.

**Comment by PeterKottas** [comment]
Yeah @avisonmaher it totally right. This is standard way of creating executables with dot net core these days. It's therefore not an issue with this lib so I'll be closing this now. Thanks
