### ISSUE TITLE
How can I create service to run on Windows and Linux?

### ISSUE THREAD

**Issue by reinaldocoelho** [PeterKottas/DotNetCore.WindowsService#48]
Hi!

With this library, can I create an service to run on Windows and Linux?
And how can I do that?

Thank you!

**Comment by PeterKottas** [comment]
Hi there, nope, as the name of it suggests, this is just for windows. I don't have much experience with Linux but I think you can setup a "service" there easily without any library.

**Comment by reinaldocoelho** [comment]
Thank you @PeterKottas!

I want to create a service multi-platform, using the same code to run on windows and linux.
But for now it´s don´t work.
I will try to use your lib in parallel with Linux service.

If work´s well, I attach the sollution in here.

:-) Thank you!

**Comment by PeterKottas** [comment]
Sounds good, let me know how it goes ;)

**Comment by xts-velkumars** [comment]
@reinaldocoelho 
Any updates for Linux box?
