### ISSUE TITLE
ExampleService works if I run through VS, but not with dotnet command

### ISSUE THREAD

**Issue by Sepaphoria** [PeterKottas/DotNetCore.WindowsService#5]
Hello,

I'm having an issue when I install your ExampleService (non-timer version to simplify it).  If I edit the ServiceRunner, line 18 to manually specify ActionEnum.Install, I can get the ExampleService to install and run on my **Windows 10** box.  However, I have an issue when I attempt to install and run the ExampleService via dotnet commands.  Here's what I'm doing:

_**Steps**_
1.  Open Admin command prompt and navigate to the folder PeterKottas.DotNetCore.Example on my harddrive.
2.  Issue **dotnet publish** command while in that directory
3.  Subsequently nav down to ..\bin\Debug\netcoreapp1.1\win81-x64\publish (where thePeterKottas.DotNetCore.Example.dll) is located
4.  Issue **dotnet PeterKottas.DotNetCore.Example.dll action:install** command

_**Result**_
The **_service installs_** and shows up in the Services mmc.  However, it **_won't start_**.  The error I receive is _"The service did not respond to the start or control request in a timely fashion"_.  I thought it might be a permissions issue, but if I use box admin credentials manually on the installed service, it still won't start.

Any ideas?

**Comment by Sepaphoria** [comment]
_**Update**_
I was able to get it to work _outside_ of the IDE.  I had to target a specific runtime in my project.json (win10-x64 in my case) so my own console application would generate an **exe**.  I then did the publish, navigated to the publish directory and _**didn't use dotnet**_ to run it.  Instead I ran the exe with action:install and it worked!

I hope that helps you, I know I was struggling a bit with this.

**Comment by PaulCoetser** [comment]
Thank you so much.  I will give this a try!

**Comment by PeterKottas** [comment]
Morning guys, thanks Sepaphoria, that definitely works :) that's actually what I was doing with all my services so I never even encountered this, gave it a shot yesterday and the indeed is a problem with running even the simplest code with dotnet. I have an idea on what I could try but for now feel free to use that *.exe approach. Portable apps seem to work just fine. I'll let you both know when I have any news about this. @PaulCoetser I will use this issue as it specifically meant to solve this problem.

**Comment by PeterKottas** [comment]
Hi @Sepaphoria & @PaulCoetser  . Good news. I've fixed the problem and the solution is now available via nuget. Release version is 1.0.13. Would be great if you could try it so that I can close the issue :) There's also one minor fix. I've seen the service fail to reinstall from time to time saying the service is marked for deletion. This is now handled via retries and all works well.
