### ISSUE TITLE
Can't extra run arguments

### ISSUE THREAD

**Issue by DercioGaspar** [PeterKottas/DotNetCore.WindowsService#50]
Is there any way to send a custom parameter on action:install so that the action:run passes it every time the service is started?

What it supports:
dotnet.exe C:\Path\Service.dll action:install -> dotnet.exe C:\Path\Service.dll action:run

What I need:
dotnet.exe C:\Path\Service.dll param action:install -> dotnet.exe C:\Path\Service.dll param action:run

What it currently does when I try to pass the param:
dotnet.exe C:\Path\Service.dll param action:install -> dotnet.exe C:\Path\Service.dll action:run

**Comment by PeterKottas** [comment]
Hi there, this code right here https://github.com/PeterKottas/DotNetCore.WindowsService/blob/master/Source/PeterKottas.DotNetCore.WindowsService/ServiceRunner.cs#L170 is responsible for copying extra arguments over to the service command. It seems to me you are configuring it wrong. 
The thing is you should never use action:run, you only use action:install, that way it installs and the service command becomes "What you need". Hope that helps ;) I won't be closing this right away but I am pretty sure you'll close it yourself soon while you give this a go. GL

**Comment by DercioGaspar** [comment]
I had seen that line before I opened the issue (and yes I'm only using install and I can make everything work but the param), but it seems to me that it can only takes some allowed params because of this line https://github.com/PeterKottas/DotNetCore.WindowsService/blob/master/Source/PeterKottas.DotNetCore.WindowsService/ServiceRunner.cs#L26
What I need is to pass a custom parameter and that I cannot see how to do :(

**Comment by PeterKottas** [comment]
Sorry was gone for holidays for a while. The line you highlighted just configs the lib arguments and should let other unrecognized flow into that extra arguments array. These are then concatenated to the service call. You should be able to see these in service properties in windows services.
