### ISSUE TITLE
OnStop not called intentionaly when system (Win7) shuts down?

### ISSUE THREAD

**Issue by MontyGvMC** [PeterKottas/DotNetCore.WindowsService#52]
Hi there.

Still love your library. :-)

Using your library I created a windows service running on my Win7 work machine. It does some brute force calculation stuff which is not complex but long running (brute force sudoku generating). Therefor I created it as windows service so each time the machine starts it starts automatically calculating some new sudokus.

The behaviour I experienced was that ,I implemented a function persisting the state of the generator and gets called when OnStop() is called. It works when I stop the service but OnStop() seems not get called when windows is shut down.

Is that behavior intended? (using the latest version of your library as downloaded today)

A side question: anyway to get notified when I close the console window (when not run as service but as console application)?

**Comment by MontyGvMC** [comment]
I have found a question on StackOverflow: [Killing gracefully a .NET Core daemon running on Linux](https://stackoverflow.com/questions/38291567/killing-gracefully-a-net-core-daemon-running-on-linux/38291911)

Whenever there is a need for being notified when the system shutsdown this line helps:

AssemblyLoadContext.Default.Unloading += MethodInvokedOnSigTerm

I used it in MyService : IMicroservice to call the Stop() method manually

**Comment by PeterKottas** [comment]
Hey mate, just came back from holidays and reading your issue. I must say I am not exactly sure how this should work. It feels like the stop should be called only when the service is stopped. Shutting down the pc is maybe not stopping per say. More like a termination. It might make sense to add another callback (OnShutdown) and use the solution that you proposed to call it. Or just call OnStop instead? Just thinking out loud here TBH.

**Comment by dasMulli** [comment]
This would be possible in a custom state machine instead of `IWin32Service`.. I haven't had any request or the need for a shutdown event so I haven't implemented any convenience API for it. But the event can be registered for in windows' service management system. `ServiceBase` has an `OnShutdown()` function that can be used for this.

**Comment by PeterKottas** [comment]
Fixed by https://github.com/PeterKottas/DotNetCore.WindowsService/releases/tag/v2.0.7. Feel free to reopen if you find any issues with the current solution.
