### ISSUE TITLE
Run as network service

### ISSUE THREAD

**Issue by eman1986** [PeterKottas/DotNetCore.WindowsService#53]
I'm looking to use .NET Core for a new windows service and the biggest hold off on switching to core was the lack of topshelf.

I love how your library looks and feels like topshelf, one thing I'm stuck on is how to get the service to log in as Network Service like Topshelf lets you.

Also is there any trick on getting this to work with IoCs?

**Comment by PeterKottas** [comment]
Hi @eman1986, yeah makes sense. I'll look at adding this in the next few days ;)

**Comment by PeterKottas** [comment]
Ok work is done and released. Could you please test the latest release to see if it works as expected? 

Release : https://github.com/PeterKottas/DotNetCore.WindowsService/releases/tag/v2.0.3

From the updated readme :
...
Run the service with built-in-account:(NetworkService|LocalService|LocalSystem) and action:install which installs it for the given built in account. Defaults to LocalSystem.
...

**Comment by eman1986** [comment]
thaNks, I'll give it a try sometime this week 😄

**Comment by PeterKottas** [comment]
Ok np. I'll close this. Open a new issue if you find any problems with it.
