### ISSUE TITLE
Can't run action:install

### ISSUE THREAD

**Issue by allen-gopico** [PeterKottas/DotNetCore.WindowsService#58]
I've used the sample the sample template that's provided but when I've tried running the command dotnet ConsoleApp1.dll action:install it returns  

> "Service ConsoleApp1.ExampleService errored with exception : Access is denied"
![image](https://user-images.githubusercontent.com/16217318/33164271-f91bc6e4-d06c-11e7-887c-150290f90c82.png)

**Comment by PeterKottas** [comment]
You'll need to run as admin for it to work

**Comment by allen-gopico** [comment]
@PeterKottas Thanks

**Comment by PeterKottas** [comment]
Np
