### ISSUE TITLE
displayName arg doesn't work

### ISSUE THREAD

**Issue by mbuck** [PeterKottas/DotNetCore.WindowsService#59]
Display name is never set when passed in via the command line. For example:
`myservice.exe action:install displayName:DoStuff`

I believe the issue has to do with the following line:
https://github.com/PeterKottas/DotNetCore.CmdArgParser/blob/f5d012866e08bd7cf4e677bc55c5cf030d95665f/Source/PeterKottas.DotNetCore.CmdArgParser/Parser.cs#L39
This results in `"displayname".StartsWith("displayName")` which evaluates to false.

I noticed this is the only camel cased argument, while others are kebab cased. Perhaps this is the reason for this issue? Would it be possible to use "display-name" or "displayname" instead? I'm happy to throw together a pr, but I wanted to make sure that the change was in the desired direction first.

**Comment by PeterKottas** [comment]
Thanks for reporting this. It indeed seems it's a problem. I'll fixed this right now. Sorry about the delay, I only have time to maintain this lib from time to time.

**Comment by PeterKottas** [comment]
Fixed by https://github.com/PeterKottas/DotNetCore.WindowsService/releases/tag/v2.0.4

**Comment by mbuck** [comment]
Awesome. Thanks for looking into it!

**Comment by PeterKottas** [comment]
Np ;)
