### ISSUE TITLE
[WIX] Cannot run service after installing (error 1053)

### ISSUE THREAD

**Issue by Patryx** [PeterKottas/DotNetCore.WindowsService#60]
Hi!
I hope you can help me. I used your library to create a service using dotnet core. I built WIX installation which installs windows service (using typically ServiceInstall and ServiceControl without arguments), then installed the service with administration privilages. Unfortunately I cannot run the service from services.msc. I am always getting error 1053 ("The service did not respond in a timely fashion").
Any idea how to install such a service using WIX and can start and stop service normally via Services.msc? 
I would be grateful for helping.

**Comment by RamazanBIYIK** [comment]
Same issue. I used "New-Service -Name MyServiceName -BinaryPathName "C:\Users\Ramazan\source\repos\AlertMailWindows
ServiceonCoreConsole\**run.bat** action:run" -StartupType Automatic" to install service.(There is only "dotnet run" command inside batch file )I am dealing with a database that will check the parameters and notify somebody via e mail. I wrote classes and make a base class. I called baseclass inside Start method and used a timer(to check database every 30 sec. ). Also ı used " Microsoft.Extensions.Logging" nuget package.

**Comment by Patryx** [comment]
So how your CustomAction look like and the InstallExecuteSequence? 
Is it possible to use 'dotnet run action:install' directly in ExeCommand? And how do unistall service before uninstallinh. After building project I have *.exe file. Do you have it too?

**Comment by RamazanBIYIK** [comment]
I finally get it worked. First of all install peter's repo. There is an example project there. It worked fine in my computer so the problem was on my project.

The steps ı followed:
1-) There was a class inside peter's repo. And there was timer so ı needed that class ı just modify it for myself,
2-)Open CMD and type: dotnet yourdll.dll action:run ı get an error that saying "The service process could not connect to the service controller" . Dont lose hope :D
3-) Then ı typed dotnet YourDll.dll action:install

Now ı ll try my service and let you know if it is working

**Comment by RamazanBIYIK** [comment]
It didn't work as ı expected :( Probably the problem is inside my codes.

**Comment by Patryx** [comment]
Remember to put everything in thread/timer etc. OnStart have to be finished quickly

**Comment by RamazanBIYIK** [comment]
I think ı put. I logged information to  text files. ı used a locker object for not crash threads,(timer set as 1 sec and my operation takes 5 sec).  While you are saying thread/timer you mean tasks? I didn't used tasks structer in my project. My project have 3 stage after get inside ElapsedEventArgs class
1-)Get a list from SQL datatable where  parameters false.
2-) get that parameters ID and send notification via email.
3-) update paramaters to true.

**Comment by PeterKottas** [comment]
Guys please follow the docs in the readme. You should never use New-Service -Name, if you could there would be no need for this lib. dotnet YourDll.dll action:install is indeed the right way. Start simple to make sure the lib is working. Then add more things. Make sure you run as admin. The timer service should indeed be good starting point for you judging by your requirements.

**Comment by RamazanBIYIK** [comment]
I think ı put. I logged information to  text files. ı used a locker object for not crash threads,(timer set as 1 sec and my operation takes 5 sec).  While you are saying thread/timer you mean tasks? I didn't used tasks structer in my project. My project have 3 stage after get inside ElapsedEventArgs class
1-)Get a list from SQL datatable where  parameters false.
2-) get that parameters ID and send notification via email.
3-) update paramaters to true.
4-)Repeat that sequence every 20 sec.

Everything was goin fine . Service get inside ElapsedEventArgs class. But while it is counting the false paramater inside sql table it is doing nothing. I am confirmed that with a textfile. It cant pass that line.

**Comment by Patryx** [comment]
Peter, after correcting my source codes of service, I resolved the problem with WIX installer in a bit different way (I did it before your answer).
 In VS2017 as a result of compilation of Console Appliaction (let's say "TestApp") I get "TestApp.exe" file and "TestApp.dll". I don't know why there is also a exe file but in WIX installer I used two CustomAction's:
- one to install service after installing files as call: "TestApp.exe action:install 'name:TestService'" 
- second one to uninstall service just befote uninstalling files: "TestApp.exe action:uninstall 'name:TestService'".
It seems to work now. Do you see any dangers? Maybe I shouldn't get and use *.exe application (I don't know why it is generated and it isn't in your example...) in this way to install i uinstall the service.
Please give me your opinion.
Thanks in advance.

**Comment by PeterKottas** [comment]
Good job again! Glad we have a wix expert in da house as it seems people are using it.
