### ISSUE TITLE
Wix Installation

### ISSUE THREAD

**Issue by HolyOne** [PeterKottas/DotNetCore.WindowsService#64]
Because .net core console  application is a dll file and it needs dotnet.exe to run,
I am confused about how to register it as a service with a wix installation script.

Can you provide an example or give a more clear example how to install the dll file as service from the command line ? thanks

**Comment by PeterKottas** [comment]
I have no idea how wix works, never used it tbh, nor I feel the need to. Dotnet can create self contained apps (exe), I would look into that as it seems to be what you're after.

**Comment by avisonmaher** [comment]
In a word CustomAction. I created a custom action that Exec="cmd /s /c &quot;MyWindowsService action:install&quot;"

and then using a custom dialog to overwrite the mondo ui, I added a DoAction with the value of the customaction Id to execute on exit.

**Comment by PeterKottas** [comment]
Nice work @avisonmaher, that seems like the way to go! I'll close this for now and I am sure it will be useful for somebody later on. Thanks
