### ISSUE TITLE
Revise or Eliminate Step 18?

### ISSUE THREAD

**Issue by markolbert** [PeterKottas/DotNetCore.WindowsService#65]
Thanx for putting this lib together, Peter. I'm using it to try and get a netcoreapp2.0 project running as a Windows service.

I ran into the same "the service is not starting up in a timely fashion" reported in another issue, after trying to install the netcore dll produced in the example project as a service.

Might I suggest deleting or revising step 18 in the Usage section on the home page? That's what I prompted me to go the way I did. But apparently, based on your response in that other issue, that's not the way to install services based on the library.

**Comment by PeterKottas** [comment]
Hi Mark, thanks for your input, I actually never tried that. It was suggested as usage with power-shell by somebody here in community. I'll change it to what I think should work right now, can you give that a go then pls?

**Comment by PeterKottas** [comment]
In fact, looking at it now it was total nonsense, must have been half asleep when I put it there. All should be proper now.

**Comment by markolbert** [comment]
Yep, the revised #18 works fine. Thanx for the quick response!

**Comment by PeterKottas** [comment]
Np, happy coding ;)
