### ISSUE TITLE
Power Event Handling?

### ISSUE THREAD

**Issue by markolbert** [PeterKottas/DotNetCore.WindowsService#67]
The service I'm writing needs to take action when the system returns from a sleep state. From looking over the service documentation, I think that means responding to a power-related action that's not currently implemented in the WindowsService library...but I could be missing something.

If it does need to be implemented, it looks like I'd have to tweak ServiceRunner, HostConfigurator and maybe ServiceConfigurator.

I'd be interested in your thoughts on whether there's a better approach. Also on whether you tried to implement that functionality and ran into problems :)

**Comment by PeterKottas** [comment]
Nope never had to do that. I am wondering, isn't it that same as onStart? Or maybe onResume? In fact onResume might be called on wake up. But you'll have to check. No plans so far to support that but obviously PR would be much appreciated :)

**Comment by dasMulli** [comment]
@markolbert this library runs services by implementing [`IWin32Service`](https://github.com/dasMulli/dotnet-win32-service/blob/a87bad6642c35afe906bf3dec5bd6a5acb237948/src/DasMulli.Win32.ServiceUtils/IWin32Service.cs) from https://github.com/dasMulli/dotnet-win32-service, which can only do start and stop.

More power functionality (pun intended) is available through custom a [`IWin32ServiceStateMachine`](https://github.com/dasMulli/dotnet-win32-service/blob/a87bad6642c35afe906bf3dec5bd6a5acb237948/src/DasMulli.Win32.ServiceUtils/IWin32ServiceStateMachine.cs). The basic `IWin32Service` is just a state machine implementation by itself - [`SimpleServiceStateMachine`](https://github.com/dasMulli/dotnet-win32-service/blob/a87bad6642c35afe906bf3dec5bd6a5acb237948/src/DasMulli.Win32.ServiceUtils/SimpleServiceStateMachine.cs). You could take it as an example and see where you can take it.
Not sure how/if that can be conveniently surfaced through `DotNetCore.WindowsService`'s abstractions, but this is where you could start if you really need it. I didn't have a need or even requests for pause/resume functionality which could also be implemented this way.

About the power stuff: the main callback that the state machine calls is to report its state, which has a flag enum indicating which commands are accepted in the current state. This flag enum also has an [value for power events](https://github.com/dasMulli/dotnet-win32-service/blob/a87bad6642c35afe906bf3dec5bd6a5acb237948/src/DasMulli.Win32.ServiceUtils/ServiceAcceptedControlCommandsFlags.cs#L60). The command handling function of the state machine will then be called with a corresponding power event control command.

**Comment by markolbert** [comment]
Thanx, @PeterKottas  and @dasMulli, for the feedback. I think I've come up with a way to obviate a need to worry about anything other than start and stop, but right now I'm deep in the weeds building a UI for managing the service's configuration.
