### ISSUE TITLE
Changing to NetStandard

### ISSUE THREAD

**Issue by Ulimo** [PeterKottas/DotNetCore.WindowsService#68]
Hi!
I just forked your project and tested changing it to NetStandard instead of NetCoreApp, and from my testing it seems to work fine with both a test project against net461 and NetCoreApp.
This is just a simple 1 line change so a pull request seemed to much of a hassle :)

But the benefits will be good, making it possible to create exe's as well!

**Comment by dasMulli** [comment]
This library has a nuspec as well that would need updating..
@PeterKottas why is there a need for a nuspec? did `dotnet pack` not do the trick? (all properties can be set in csproj files or a `Directory.Build.props` file)

**Comment by PeterKottas** [comment]
@Ulimo Doesn't make sense to make it an net standard, by definition netstandard should be cross platform and this isn't as it relies on windows to run. It would run, like you've said (on windows) but not max/linux so I guess it makes sense to leave it as is. You should be able to do all you want with it anyways. 
@dasMulli is it just me or I fail to see connection between this issue and your question? Anyways, I have a nuspec cause I am used to it, my usual build script handle some logic that dotnet pack couldn't handle so to keep it consistent, I went nuspec for everything. I think for normal people, dotnet pack will work no probs.

**Comment by dasMulli** [comment]
no connection, would just have linked it to existing issues or create one on respective tooling repos so others could benefit as well from improvements :)
