### ISSUE TITLE
Detect if running as service or console?

### ISSUE THREAD

**Issue by HolyOne** [PeterKottas/DotNetCore.WindowsService#69]
How can I detect if my app is running as service or console application?

**Comment by PeterKottas** [comment]
this is intended for running windows services. The console host is basically just a tool to help you debug. So would highly recommend not to put logic in it that depends on the host. It should ideally be considered always a service.

**Comment by dasMulli** [comment]
It's quite hard to do that in .NET Core. In classic .NET, there is `Environment.UserInteractive` which calls a very.. interesting.. windows API behind the scenes (checks a "Window station has visible display surfaces" flag). In .NET Core this always returns `true` on all platforms AFAIK and I have no idea what that returns in a docker environment, remote PS sessions or GUI-less windows servers..
TopShelf checks if the name of the partent process is "services" to test if the application has been started from a service management process.
You're usually better off not needing to know how you have been launched..

**Comment by medial-research** [comment]
Same need here.

I am running some endless tasks in the OnStart. As these are endless tasks, In the console app implementation I have a Task.WaitAll() which will practically keep the console app endlessly running. When used here as a windows service, this Task.WaitAll() is not needed as they are now nested in your Task.Run thread.

How would I the identify and skip console-oriented Task.WaitAll() ?

**Comment by PeterKottas** [comment]
I suggest to keep things simple. 
What I do is 
#if DEBUG
    Console.WriteLine("Debug version");
#endif
And put my "wait" code there. You are not meant to use these apps as console apps, only as services. That's why it's ok to have that extra bit there for debugging imho.

**Comment by ducttapecoder-vt** [comment]
> I have no idea what that returns in a docker environment, remote PS sessions or GUI-less windows servers..

Sorry to necrobump but just ran into this, it seems docker containers return false for this which is a problem.

**Comment by vbulcan** [comment]
Here:
https://docs.microsoft.com/en-us/dotnet/api/system.environment.userinteractive?view=netcore-3.1
