### ISSUE TITLE
Runs from project folder. Fails from publish folder

### ISSUE THREAD

**Issue by DBFBlackbull** [PeterKottas/DotNetCore.WindowsService#70]
Hello.

I have tried to use the simple template that you have provided to test with.
My problem is that whenever I run my application from the project folder (the code) then it runs fine without any problems.
When I then publish my project and try to run it from the publish folder, then I get an error that my system cannot find the System.Runtime.

Here is an example of what I've done up to this point:
- Installed the nuget package
- Installed the template
- Build and run from from the commandline with no problem
- Publish and run from commandline with HUGE problems

`D:\git\test\ConsoleApp1>dir
 Volume in drive D is Data
 Volume Serial Number is CE11-6B0D

 Directory of D:\git\test\ConsoleApp1

17-01-2018  11:02    <DIR>          .
17-01-2018  11:02    <DIR>          ..
17-01-2018  11:02    <DIR>          bin
17-01-2018  10:56               301 ConsoleApp1.csproj
17-01-2018  11:02               309 ConsoleApp1.csproj.user
17-01-2018  11:00             1.138 ExampleService.cs
17-01-2018  11:02    <DIR>          obj
17-01-2018  11:01             1.536 Program.cs
17-01-2018  11:02    <DIR>          Properties
               4 File(s)          3.284 bytes
               5 Dir(s)  72.521.216.000 bytes free

D:\git\test\ConsoleApp1>dotnet run action:install
Successfully registered and started service "ConsoleApp1.ExampleService" ("No description")

D:\git\test\ConsoleApp1>dotnet run action:uninstall
Successfully unregistered service "ConsoleApp1.ExampleService" ("No description")

D:\git\test\ConsoleApp1>dotnet publish
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 18,67 ms for D:\git\test\ConsoleApp1\ConsoleApp1.csproj.
  ConsoleApp1 -> D:\git\test\ConsoleApp1\bin\Debug\netcoreapp2.0\ConsoleApp1.dll
  ConsoleApp1 -> D:\git\test\ConsoleApp1\bin\Debug\netcoreapp2.0\publish\

D:\git\test\ConsoleApp1>cd bin\Debug\netcoreapp2.0\publish

D:\git\test\ConsoleApp1\bin\Debug\netcoreapp2.0\publish>dir
 Volume in drive D is Data
 Volume Serial Number is CE11-6B0D

 Directory of D:\git\test\ConsoleApp1\bin\Debug\netcoreapp2.0\publish

17-01-2018  11:27    <DIR>          .
17-01-2018  11:27    <DIR>          ..
17-01-2018  11:27             9.668 ConsoleApp1.deps.json
17-01-2018  11:12             7.680 ConsoleApp1.dll
17-01-2018  11:12             1.328 ConsoleApp1.pdb
17-01-2018  11:27               154 ConsoleApp1.runtimeconfig.json
09-11-2016  19:41            19.968 DasMulli.Win32.ServiceUtils.dll
14-11-2016  20:41            16.376 Microsoft.Extensions.PlatformAbstractions.dll
24-01-2017  18:37            10.240 PeterKottas.DotNetCore.CmdArgParser.dll
14-12-2017  16:53            30.208 PeterKottas.DotNetCore.WindowsService.dll
17-01-2018  11:27    <DIR>          runtimes
19-07-2017  09:01            27.944 System.ServiceProcess.ServiceController.dll
               9 File(s)        123.566 bytes
               3 Dir(s)  72.520.974.336 bytes free

D:\git\test\ConsoleApp1\bin\Debug\netcoreapp2.0\publish>ConsoleApp1.dll

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

D:\git\test\ConsoleApp1\bin\Debug\netcoreapp2.0\publish>ConsoleApp1.dll action:install

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

D:\git\test\ConsoleApp1\bin\Debug\netcoreapp2.0\publish>cd ..

D:\git\test\ConsoleApp1\bin\Debug\netcoreapp2.0>ConsoleApp1.dll action:install

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.`

**Comment by dasMulli** [comment]
You need to run the dll using `dotnet ConsoleApp1.dll`. this is not an executable file like classic .NET applications.

**Comment by DBFBlackbull** [comment]
Thank you @dasMulli 
This worked. I feel so dumb for overlooking the dotnet command =/

**Comment by dasMulli** [comment]
you're welcome.
I posted at a partially related issue (https://github.com/dotnet/sdk/issues/1912#issuecomment-361366046). The fact that the dll is actually runnable isn't very helpful for developer's diagnostic efforts..
