### ISSUE TITLE
Doesn't work in .NET Core 2.0 project

### ISSUE THREAD

**Issue by justintoth** [PeterKottas/DotNetCore.WindowsService#72]
In a .NET Core 2.0 project, using the latest version of your nuget package gives the following error:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS1705	Assembly 'PeterKottas.DotNetCore.WindowsService' with identity 'PeterKottas.DotNetCore.WindowsService, Version=2.0.5.0, Culture=neutral, PublicKeyToken=null' uses 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' which has a higher version than referenced assembly 'System.Runtime' with identity 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'	AmpUp.MessageBroker	C:\RPR-AMP-Upstream\Dev\AmpUp\AmpUp.MessageBroker\AmpUp.MessageBroker\CSC	1	Active

**Comment by PeterKottas** [comment]
I guess you are not starting it as administrator, which you should

**Comment by justintoth** [comment]
I am running Visual Studio 2017 as an Administrator. It only works with .NET Core 1.0, .NET Core 2.0 gives the above error.

**Comment by MiguelCosta** [comment]
Sorry, but I think is not a problem with DotNetCore.WindowsService because I have a project in .NET Core 2.0 and it works fine.

**Comment by justintoth** [comment]
Yeah I was able to get it working, I just had to remove and readd the nuget packages. Must've been something funky that happened when I upgraded to .NET Core 2.0.
