### ISSUE TITLE
Extra Argument

### ISSUE THREAD

**Issue by rydergillen-compacSort** [PeterKottas/DotNetCore.WindowsService#74]
I have been using this library for a while however I cannot for the life of me figure out how to pass an EXTRA argument. Any arguments I append to the end of the install command are dropped.

The Service Path Should be: C:\MyService.exe action:run arg1:MyArg

Please Help

**Comment by PeterKottas** [comment]
Sorry, I am kind of swamped right now so I wasn't able to look into this. what I suggest is cloning the repo and giving it a go locally. It's fairly simple, if there's a big you should be able to spot it no probs. I myself never needed this functionality therefore I just added it "blindly" so it might not be working properly. It would be weird though cause there's quite a few people using it and I would be surprised if you were the first one to try this. But you never know. Worst case I'll give it a go in few days/weeks as time allows

**Comment by rydergillen-compacSort** [comment]
I was able to get it working, it looks like there is a minor bug... there is some code that drops the 1st argument if the App is a standalone exe (opposed to .dll). I believe this was mistakenly dropping my extra argument. I was able to work around the issue by passing 2 extra arguments, the 1st is dropped and the 2nd makes it through. Not pretty but it works.

**Comment by PeterKottas** [comment]
ah yeah, I remember that, the first argument normally is the path to the dll. Or at least was when I've written it. Hence I dropped it it wasn't necessary. Ok thanks for looking into it, I'll fix it when I get to it. Good to know that you can at least work for now with that hack.

**Comment by PeterKottas** [comment]
Fixed by https://github.com/PeterKottas/DotNetCore.WindowsService/releases/tag/v2.0.7. Feel free to reopen if you find any issues with the current solution.

**Comment by dgfmdrv** [comment]
Hello, I'm using this versión of lib:
![image](https://user-images.githubusercontent.com/1451834/54121286-5ea0eb00-43fa-11e9-94f5-572f8dbb9168.png)

I launch this command to register the service:
"SePro TS OPCUASwitch Client Service.exe" "name:SeP..." action:install uno dos tres

The service has two parameters and "one" parameter is lost:
![image](https://user-images.githubusercontent.com/1451834/54121490-da029c80-43fa-11e9-8d35-8a873ebb6ddd.png)

Thank you for this library :-)
