### ISSUE TITLE
Website vs Websocket

### ISSUE THREAD

**Issue by samcov** [PeterKottas/DotNetCore.WindowsService#75]
You mention that this is not good for websites, and I'm assuming the thought there is that you're serving web pages, etc.

However, our app(s) are more data intensive over websockets(via SignalR), calling microservices and returning data to clients.

My additional assumption is that this type of app does not fall into the website area, please correct me if I'm wrong, thanks!

**Comment by PeterKottas** [comment]
in this case you will want to have a "website" which serves signal-r as a separate thing. This website (website in this context means proper dot net core web application that does nothing with my lib) will then talk with microservices via some sort of mechanism (wcf/massaging queue/whatever) and these microservices will be the ones that use my lib.

**Comment by samcov** [comment]
Odd to hear you say that, what networking protocol would talk to your library? Everything you mentioned will communicate messages using sockets, pipes, etc, otherwise how could you ever get information into your libs?

All SignalR does is pass messages to services, that's it's purpose, and just what you described. BTW, we did this in the full .net framework and is a standard pattern for SignalR to be hosted in a windows service.

**Comment by PeterKottas** [comment]
Nah I think we don't understand each other properly. I'll try it again :)

This library was meant to create services that are not directly web facing per say. Cause it's not necessary. You can in fact achieve this using already existing tools. More detials here : https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?tabs=aspnetcore2x

However, often will you see a need of creating micro services with which you don't want to rely on the whole aspnetcore ecosystem, basically you just want these to be console apps running as a service. None of 
```
var host = WebHost.CreateDefaultBuilder(args)
        .UseContentRoot(pathToContentRoot)
        .UseStartup<Startup>()
        .UseApplicationInsights()
        .Build();
```
Just pure plain old console app with some logic in it. And that's what this lib is for. I am not saying you wouldn't be able to make websockets work from windows service created using my lib. Chance are you would succeed, but in my mind, it's redundant. It's much better to have a web facing layer (which uses web api or signal-r or websockets or any other web facing technology) and then have these microservices that handle logic. Communication between the web facing layer and these micro services is a different concern. However for that, I would strongly advocate against web sockets and rather go for messaging layer like rabbit-mq as that's the technology that is more appropriate. Web sockets are meant for interactive web-server <-> client communication. Interactive in this sense mostly mean bi-directional. 

Hope this clears it up ;)

**Comment by samcov** [comment]
Yes, that's MUCH clearer, sorry for the confusion, and I think our point is very valid!
