### ISSUE TITLE
Add .NETFramework,Version=v4.7.1 as Target framework

### ISSUE THREAD

**Issue by BjornDeRijcke** [PeterKottas/DotNetCore.WindowsService#76]
Hello,

It is currently impossible to use your library on a .net core console app that targets the full .Net framework.

For us this would be necessary to use your library as we currently have a windows service that we need to port to a .net core console app, but one that does target net471.

Would this be possible? dasMulli's dotnet-win32-service package can be installed when targeting net471, but I'd rather use your wrapper if possible, it is more convenient. 

Greetings,

**Comment by BjornDeRijcke** [comment]
Perhaps for additional detail, having the following in your csproj:
`<TargetFramework>net471</TargetFramework>
    <RuntimeIdentifier>win7-x86</RuntimeIdentifier>`

Results in this error:

> Package PeterKottas.DotNetCore.WindowsService 2.0.5 is not compatible with net471 (.NETFramework,Version=v4.7.1). Package PeterKottas.DotNetCore.WindowsService 2.0.5 supports:
>   - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
>   - netcoreapp1.1 (.NETCoreApp,Version=v1.1)
>   - netcoreapp2.0 (.NETCoreApp,Version=v2.0)
> Package PeterKottas.DotNetCore.WindowsService 2.0.5 is not compatible with net471 (.NETFramework,Version=v4.7.1) / win7-x86. Package PeterKottas.DotNetCore.WindowsService 2.0.5 supports:
>   - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
>   - netcoreapp1.1 (.NETCoreApp,Version=v1.1)
>   - netcoreapp2.0 (.NETCoreApp,Version=v2.0)
> Package restore failed. Rolling back package changes

**Comment by PeterKottas** [comment]
Solved in https://github.com/PeterKottas/DotNetCore.WindowsService/releases/tag/v2.0.6

**Comment by BjornDeRijcke** [comment]
Thanks!

**Comment by PeterKottas** [comment]
Np ;)
