### ISSUE TITLE
self contained apps

### ISSUE THREAD

**Issue by jchannon** [PeterKottas/DotNetCore.WindowsService#78]
In the README it says you should use `dotnet myapp built-in-account:NetworkService action:install` but if you publish the app you end up with a binary so does the following work `myapp.exe built-in-account:NetworkService action:install` ?

**Comment by PeterKottas** [comment]
It should but as I am not using it, it's not very high priority for me to make it work. If it doesn't feel free to clone it and glance at what the problem is. I'll be happy to release it asap if you fix something but can't spend much time in the following weeks working on this.

**Comment by jchannon** [comment]
works fine as a self contained app, thanks

**Comment by PeterKottas** [comment]
👍
