### ISSUE TITLE
Behavior of Ctrl+C

### ISSUE THREAD

**Issue by samcov** [PeterKottas/DotNetCore.WindowsService#79]
If I run the minimal example, the app runs and quits when it's done.

I created a project that actually does something and when it quits, I get the hit Ctrl+C, and when I do it quits properly. It also said the app could not quit at this time, or something like that.

**Questions:**
1. Why the behavior difference, and
2. What would the behavior be in the released service?

Thanks.

**Comment by PeterKottas** [comment]
I am not exactly sure without seeing some code. In general ... Running as console app runs a proper console app. Therefore it quits if you don't setup some idle loop or wait for something async to happen. 
With service it's a bit different, service will continue running as the implementation differs slightly. You can try that easily, just setup some logging to a file and observe. There's an example with this as well.

**Comment by samcov** [comment]
Yes, I am awaiting an async function in the Example Service start. I can send you the code if it helps, I have a fully standalone solution... oh well, I'll just attach it.

I'm wondering if this will be an issue?
[HelloWorld.NetCore.zip](https://github.com/PeterKottas/DotNetCore.WindowsService/files/1735014/HelloWorld.NetCore.zip)

**Comment by samcov** [comment]
After further testing, I ran the project in powershell(dotnet silohost.dll), and it behaves properly.

I wonder if running it in the IDE with breakpoints in the wrong place throws things off, specifically the timing when breaking in the start and close events. 

It also works when deployed as a service as far as I can tell. By that I mean it starts and stops without any problem. I'll close this one, but would like your opinion on the question below.

Will the Console.Write's cause any problem when deployed as a service?

**Comment by PeterKottas** [comment]
Ok glad to hear everything works now. Nope you can freely use Console api although I'd say it's not the best practice. I recommend to swap it for some proper logging mechanism especially if you care about the output. One thing I often do though is have a line like this in the begging of the file:
```
Console.Title = "Auth service";
``` 
Which helps identify the correct window. (I have a lot of these). And it doesn't complain in service mode so you're safe.

**Comment by samcov** [comment]
Great, I was more concerned about  having to remove them, they great for testing... Thanks
