### ISSUE TITLE
Unable to build the WindowsService

### ISSUE THREAD

**Issue by samcov** [PeterKottas/DotNetCore.WindowsService#80]
Since I don't have .Net 4.7x on my machine, it causes the project to fail.

Not quite sure how you would handle this, but there it is.

**Comment by PeterKottas** [comment]
Not sure what you mean by that. This works with Dot net core SDK. There's fallback to 4.7.1 but this is intended for Dot net core SDK

**Comment by samcov** [comment]
It can't fall back to something that doesn't exist, and it looks for it on startup in VS.

Try to compile on a machine **without** the full framework on it and it won't succeed.

I made it work by manually editing the csproj to _exclude_ 4.7.1.

**Comment by PeterKottas** [comment]
Hmm so you say you have dot net core installed but it complains just because you don't have full framework? Ok I might need to take another look at it then.

**Comment by samcov** [comment]
You may want to weigh the _"best use of your time"_ on this one.

It was trivial for me to remove it in the csproj, and I may be an outlier in not having the full framework on my laptop.

**Comment by PeterKottas** [comment]
Cool, fair enough tbh, I'll keep it in the back of my mind. Thanks

**Comment by samcov** [comment]
No problem...
