### ISSUE TITLE
.net standard 2.0 compatibility 

### ISSUE THREAD

**Issue by Dundret** [PeterKottas/DotNetCore.WindowsService#81]
Would be awesome to be able to use this in a class library that targets .net standard. What dependency does it have to force you to use it in a .net core project only? dasMulli's lib that was used does not have this requirement and can be used targeting .net standard.

**Comment by parallelbgls** [comment]
Test

- Directly set project to netstandard20
- Nuget install with no error
- Service console run with no obvious error
- Service install with no obvious error

Please add netstandard20 to project as soon as possible.

**Comment by Dundret** [comment]
What do you mean? My project is directly set to netstandard2.0.

`<TargetFramework>netstandard2.0</TargetFramework>`

when i try to install the nuget package i get a "Package restored failed. Rolling back changes for 'xxx'.

**Comment by parallelbgls** [comment]
This project is set to net471 and netcoreapp2.0, so that you could not set netstandard20 to reference this project. Clone this project and modify csproj to netstandard20. Reference to your clone project and remove Nuget reference.

**Comment by parallelbgls** [comment]
Remember .net standard library project could reference .net standard library project only.

**Comment by PeterKottas** [comment]
We cannot use standard as far as I know because standard is by design cross platform. This isn't because it only runs on windows
