### ISSUE TITLE
v2.0.3 doesn't throw a NullReferenceException when Stopped but v2.0.4+ does

### ISSUE THREAD

**Issue by dharmaturtle** [PeterKottas/DotNetCore.WindowsService#82]
When I install then reinstall the timer based example with v2.0.3, there is no null exception. However, v2.0.4 onwards throws a null error. This is simple to recreate, but I have no idea how to go about debugging it.

This is related to #66.

**Comment by dharmaturtle** [comment]
![image](https://user-images.githubusercontent.com/1278803/37112803-28ac8d56-2209-11e8-8fc2-003570ff98fb.png)


Okay, I tried a bit harder and found two points in the code that I think are relevant, namely the methods `Run(Action<HostConfigurator<SERVICE>> runAction)` and `StopService(HostConfiguration<SERVICE> config, ServiceController sc)`. However, I don't know what the expected behavior should be when `innerConfig.Service` is null (namely, when `ActionEnum` is not `Run` or `RunInteractive`). Please advise.

**Comment by PeterKottas** [comment]
Hi thanks for reporting this. Sry but I can't look at it right now. What you can try in the meantime is cloning the lib and adding some extra logging. I should have bit more time over the weekend.

**Comment by dharmaturtle** [comment]
I do exactly that (clone and added logging) in the above screenshot. However, I fully understand that your time is valuable and look forward to whenever you manage to find time to address this. Thanks!

**Comment by PeterKottas** [comment]
Cheers and thanks for understanding. I'll let you know asap.

**Comment by PeterKottas** [comment]
Fixed by https://github.com/PeterKottas/DotNetCore.WindowsService/releases/tag/v2.0.7. Feel free to reopen if you find any issues with the current solution.

**Comment by veuncent** [comment]
I am seeing this error again in 2.0.8:
```
[11:22:38 INF] Stopping service [My.Service]
[11:22:38 INF] Exception occurred in service [My.Service]
[11:22:38 ERR] Object reference not set to an instance of an object.
```
