### ISSUE TITLE
Pause/Continue

### ISSUE THREAD

**Issue by javelinco** [PeterKottas/DotNetCore.WindowsService#83]
I'm not seeing an implementation for Pause/Continue, even though the primary documentation (the readme.md) mentions you can hook up to those service events.  Am I misunderstanding something?

Thank you!

**Comment by PeterKottas** [comment]
Fixed by https://github.com/PeterKottas/DotNetCore.WindowsService/releases/tag/v2.0.7. Feel free to reopen if you find any issues with the current solution.
