### ISSUE TITLE
Stopping the service from code

### ISSUE THREAD

**Issue by bitbosse** [PeterKottas/DotNetCore.WindowsService#9]
Hi Peter,

Really like your library!

I would like to control the service and stop it when, for example an Exception in the Service.Start() method is raised. The serviceConfig.OnError callback is triggered upon the error, but I cannot figure out how to make the service stop. 

In a regular .NET application I would have used ServiceBase.Stop() method to achive this.
 
Is it possible to stop the service from within the code?

Thanks
Martin Lund

**Comment by PeterKottas** [comment]
Hi mate, glad you find it useful :) 

That definitely sounds like a viable request. I am actually surprised it never came to my mind that this is missing. 
I'll see what I can do. Won't unfortunately be as straight forward as it looks it should be. But I'll give it shot probably today after work and see what I can do.

**Comment by alex-wheat** [comment]
Hi Peter,

do you have this feature implemented?

Regards,
Alex

**Comment by PeterKottas** [comment]
Hi there, nope, sorry not just yet. Feel free to pick it up if you want. I might have some time to look into it next weekend.

**Comment by PeterKottas** [comment]
Taken care of in https://github.com/PeterKottas/DotNetCore.WindowsService/releases/tag/v1.0.20 .
