### ISSUE TITLE
action:install skips first additional argument

### ISSUE THREAD

**Issue by jaybz** [PeterKottas/DotNetCore.WindowsService#90]
Not sure if this is a bug or that first additional arguments meant something, but when running this:

`dotnet <dll> action:install some arguments here`

or this:

`dotnet <dll> some arguments here action:install`

The resulting command line for the service is this:

`dotnet <dll> arguments here action:run`

Note that the "some" argument is missing from the command line.

**Comment by PeterKottas** [comment]
Thanks for reporting the problem, I won't have time to look at this for a while but I'll keep it in mind when I'll find some time. In the meantime, feel free to tackle it yourself ;) The code is fairly simple and I am pretty sure it will just be some stupid problem in logic somewhere along these lines https://github.com/PeterKottas/DotNetCore.WindowsService/blob/master/Source/PeterKottas.DotNetCore.WindowsService/ServiceRunner.cs#L209

**Comment by jaybz** [comment]
You're right, it was a stupid logic problem with how the function checked whether the app was self-contained or not. That said, I didn't really have time to build a self contained app and check if the behavior for those is still correct. For my case at least, it behaves correctly now.

Also I don't expect any problems considering the simplicity of the change, but just so you know, I couldn't be bothered to install net471 SDK right now so I only tested against netcoreapp2.0.
