### ISSUE TITLE
Create x64 Windows service with an executable

### ISSUE THREAD

**Issue by nologinatgit** [PeterKottas/DotNetCore.WindowsService#91]
As I have learned, when a .Net Core console application is run from Visual Studio, it invokes _dotnet.exe_ and it _'hosts'_ the dll as if it was a real executable.

However, as a final release, .Net Core application can be published as an **executable** thus it can't be run with dotnet.exe.

So, I tried to use SC.EXE, and it created the service.

This is my code:

     try
      {
        ServiceRunner<MyNetCoreWindowsService>.Run(config =>
          {
            LogMessage("Runner start");
            config.SetName("MyNetCoreWindowsService");
            config.SetDisplayName("My New Service (.Net Core)");
            config.SetDescription("Desc");
            config.Service(serviceConfig =>
            {
              serviceConfig.ServiceFactory((extraArguments, controller) =>
              {
                return new MyNetCoreWindowsService(controller);
              });
              serviceConfig.OnStart((service, startParams) =>
              {
                LogMessage("Service started");
                service.Start();
              });

              serviceConfig.OnStop(service =>
              {
                service.Stop();
              });

              serviceConfig.OnError(e =>
              {
                LogMessage("OnError: " + e);
              });
            });
          });
      }
      catch (Exception ex)
      {
        LogMessage("Exception: " + ex);
      }

However, on starting the service, it doesn't work.
It hits _Runner start_, but the I get a message that the **service didn't respond to start**.

Can I somehow create a working service with an executable?

**Comment by PeterKottas** [comment]
Yeah you just use .exe and pass in commands such as action:install as detailed in readme.

**Comment by nologinatgit** [comment]
I used this command line:

> dotnet.exe D:\NetCoreService\NetCoreService\bin\Release\netcoreapp2.0\win10-x64\NetCoreService.exe action:install

When I try to install the exe, I get this error:

> Unhandled Exception: System.BadImageFormatException: Could not load file or assembly 'D:\NetCoreService\bin\Release\netcoreapp2.0\win10-x64\NetCoreService.exe'. The module was expected to contain an assembly manifest.

I definitely want to avoid that my service is run by dotnet.exe so I need to make this work.

**Comment by PeterKottas** [comment]
Don't use dotnet.exe at all, just use 
D:\NetCoreService\NetCoreService\bin\Release\netcoreapp2.0\win10-x64\NetCoreService.exe action:install

**Comment by nologinatgit** [comment]
Yeah, it worked, thanks for the clarification :)
