### ISSUE TITLE
using System.IO.FileSystem.Watcher.Polling 

### ISSUE THREAD

**Issue by beastlike** [PeterKottas/DotNetCore.WindowsService#98]
Would like to use System.IO.FileSystem.Watcher.Polling, but unfortunately it does not appear compatible, - getting this error:

error: Package System.IO.FileSystem.Watcher.Polling 0.1.0-e160210-1 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package System.IO.FileSystem.Watcher.Polling 0.1.0-e160210-1 supports: dotnet5.6 (.NETPlatform,Version=v5.6)

Is there a way to make this work, or possibly an alternative library that does the same thing? Specifically watching for files being created over a network share

Thanks!

**Comment by PeterKottas** [comment]
This lib is made for dot net core. The package you want to use doesn't support, you'll have to open an issue there or find some other lib that works on dot net core and supports the watcher polling you're after.
