### ISSUE TITLE
I can't see the service under services.msc 

### ISSUE THREAD

**Issue by velkumars** [PeterKottas/DotNetCore.WindowsService#99]
Good day, 

I have installed the service using below command, but i couldn't see the service on service.msc (windows service) 

D:\Temp\PeterKottas.DotNetCore.WindowsService.Example.exe action:install

**Comment by PeterKottas** [comment]
you have to start the console as administrator

**Comment by velkumars** [comment]
@PeterKottas yes, I'm on as administrator.

**Comment by HolisticDeveloper** [comment]
I didn't find my service at first. Although my code was using `SetName`, the Services list uses the display name. I found it listed under the full namespace of my class. Once I used `SetDisplayName` then it showed up with the name I expected.
